### ISSUE TITLE
'signWith' option produces "for-your-eyes-only"

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#100]
Hello. We've encountered that `signWith` option produces "for-your-eyes-only". 

I mean this example of code 

https://github.com/FlowCrypt/flowcrypt-android/blob/cbb8c25907b053f64e4568ba5c47493a2e3b9f49/FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpEncrypt.kt#L90

```
val builder = PGPainless.encryptAndOrSign()
            .onOutputStream(outStream)
            .toRecipients(pgpPublicKeyRingCollection)
            .usingSecureAlgorithms()

        if (pgpSecretKeyRingCollection != null) {
          val keyRings = pgpSecretKeyRingCollection.keyRings.asSequence().toList().toTypedArray()
          secretKeyRingProtector?.let { builder.signWith(it, *keyRings) }
        }
```

More details can be found here https://github.com/FlowCrypt/flowcrypt-android/issues/1095#issuecomment-814945676

It would be nice to know if "for-your-eyes-only" can be configurable

**Comment by vanitasvitae** [comment]
I agree. Will keep that in the back of my head.

**Comment by vanitasvitae** [comment]
To be clear, your code encrypts the data, hence the "for-your-eyes-only" flag. Simply signing some data *should* not result in that flag being set, but I will check.
Nevertheless, an option to set or unset the flag is a good idea.

Edit: Ah I'm wrong. The flag is also being set for signed data, as you said.

**Comment by vanitasvitae** [comment]
Looking at the rfc, the for_your_eyes_only flag can be set by setting "_CONSOLE" as file name. Would you like to have an option in the API to set a file name, or should PGPainless choose a static name (eg. "out") instead?

**Comment by DenBond7** [comment]
>To be clear, your code encrypts the data, hence the "for-your-eyes-only" flag

Just want to clarify that our case includes encrypt and sign data by one transaction.

**Comment by DenBond7** [comment]
> Looking at the rfc, the for_your_eyes_only flag can be set by setting "_CONSOLE" as file name. Would you like to have an option in the API to set a file name, or should PGPainless choose a static name (eg. "out") instead?

@tomholub Could look at this question? I'm not sure what we exactly need.

**Comment by vanitasvitae** [comment]
I made some changes to the API. The default value of the "for-your-eyes-only" flag is now false and the default file name is the empty string (as per the spec).
Additionally `onOutputStream()` has now to overloadings which allow for a custom file name and to set the fyeo flag.

**Comment by vanitasvitae** [comment]
Let me know if this suites your needs :)

**Comment by tomholub** [comment]
Looks good, thanks!

**Comment by DenBond7** [comment]
@vanitasvitae I've checked the new changes. Looks good. Thank you for the fast fix!
