### ISSUE TITLE
Question: is it possible to get decrypted file name?

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#106]
I am decrypting message with code like this:
```kotlin
      val decryptionStream = PGPainless.decryptAndOrVerify()
          .onInputStream(input)
          .decryptWith(protector, PGPSecretKeyRingCollection(listOf(pgpSecretKeyRing)))
          .verifyWith(pgpPublicKeyRingCollection)
          .ignoreMissingPublicKeys()
          .build()

      val output = ByteArrayOutputStream()
      decryptionStream.use { it.copyTo(output) }
```
However it only gives me a stream with content itself, but in the BouncyCastle `PGPLiteralData` can contain file name. Is there a way to get it?

**Comment by vanitasvitae** [comment]
I can certainly implement that into `OpenPgpMetadata`.

**Comment by IvanPizhenko** [comment]
Please do it.

**Comment by vanitasvitae** [comment]
I introduced `OpenPgpMetadata.FileInfo` which contains file name, modifiation date and encoding.

For encryption/signing, I also deprecated the recently introduced `onOutputStream(outputStream, [filename], forYourEyesOnly)` in favor of a newly introduced method `onOutputStream(outputStream, fileInfo)`.
