### ISSUE TITLE
Add method KeyRingInfo.isFullyEncrypted()

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#107]
Similar to existing `KeyRingInfo.isFullyDecrypted()`:
- Should return `true` if all keys in a secret key ring are encrypted.
- Should return `false` for a public key ring

**Comment by IvanPizhenko** [comment]
I think I can submit PR for this :)

**Comment by tomholub** [comment]
Add: gnu-dummy S2K should be skipped and not affect the outcome of isFullyEncrypted or isFullyDecrypted

**Comment by tomholub** [comment]
> Should return false for a public key ring

Maybe throw instead?

**Comment by IvanPizhenko** [comment]
@vanitasvitae what do you think about throwing? Generally makes some sense, because public keys are never encrypted, so method is effectively not applicable to them.

**Comment by IvanPizhenko** [comment]
I suggest to merge as is and think of throwing separately and add separate PR for that.

**Comment by IvanPizhenko** [comment]
+added similar methods for single key and taken into account GNU dummy S2K.
