### ISSUE TITLE
Question: how to catch MDC errors

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#108]
I am decrypting message with code like this:
```kotlin
      val decryptionStream = PGPainless.decryptAndOrVerify()
          .onInputStream(input)
          .decryptWith(protector, PGPSecretKeyRingCollection(listOf(pgpSecretKeyRing)))
          .verifyWith(pgpPublicKeyRingCollection)
          .ignoreMissingPublicKeys()
          .build()

      val output = ByteArrayOutputStream()
      decryptionStream.use { it.copyTo(output) }
```

How do I catch two following situations:
- There is no MDC
- MDC doesn't match

With the "plain BouncyCastle" I've found something like this:
```kotlin
         val data: PGPLiteral = ....
         // Do this after finished reading from the PGPLiteral data stream
         var mdcAbsent = false
          var mdcError: Boolean
          try {
            mdcError =data.verify()
          } catch (ex: PGPException) {
            mdcAbsent = ex.message?.contains("data not integrity protected") ?: false
            mdcError = !mdcAbsent
          }
```
But how to achieve the same with PGPainless?

**Comment by IvanPizhenko** [comment]
suggestion: is it possible to implement new method that finishes decryption by returning corresponding `PGPLiteralData` instead of stream? I.e.
```
val literalData = PGPainless.decryptAndOrVerify()
          .onInputStream(input)
          .decryptWith(protector, PGPSecretKeyRingCollection(listOf(pgpSecretKeyRing)))
          .verifyWith(pgpPublicKeyRingCollection)
          .ignoreMissingPublicKeys()
          .toLiteralData()
```
As I suppose (did not check) the returned stream returned by `done()` must be data stream from the `PGPLiteralData` or some wrapper over it?

**Comment by vanitasvitae** [comment]
The returned stream is a wrapper around the data stream, which checks MDCs.

Are missing/damaged MDCs something you need to deal with regularly?

**Comment by IvanPizhenko** [comment]
Absolutely. Need to check this always.

**Comment by IvanPizhenko** [comment]
I've found following in the PGPainless:
```
      val streamResult = decryptionStream.result


      streamResult.isIntegrityProtected()
      streamResult.isVerified()
```
Do these two correspond to what I have demonstrated above?

**Comment by tomholub** [comment]
> The returned stream is a wrapper around the data stream, which checks MDCs.
> 
> Are missing/damaged MDCs something you need to deal with regularly?

It's something we need to consistently check to prevent https://efail.de/ . Our desired handling is as follows:

1) if the MDC is missing when decrypting, throw an error (could be configurable if you like )
2) if the MDC is wrong when decrypting, throw an error

Presumably, 2) is already behaving that way, but 1) isn't? (didn't test personally)

**Comment by IvanPizhenko** [comment]
I'd prefer that to be status property in the decryption stream result by default, and optionally throw an exception (configurable when creating decryption stream). 
The property can be of an enum type:
```java
enum MdcCheckResult {
    SUCCESS,
    FAILURE,
    NO_MDC
}
```

or if `isIntegrityProtected` already indicates presence/absence of MDC, that can be just a boolean flag.

**Comment by tomholub** [comment]
I also like this approach, but it makes is more insecure because other library users may not realize they have to deal with MDC.

Therefore I think the default should be to throw, but make it configurable to not throw and instead return an enum. Then this should be documented. Therefore the library user has to take an extra action to have a chance of insecure usage, and hopefully there will be a big warning in the docs telling him he absolutely still has to check the enum, and don't render the message as is.

**Comment by IvanPizhenko** [comment]
Agree with @tomholub

**Comment by vanitasvitae** [comment]
I *think* PGPainless should already (at least in the signatureVerification branch) throw for invalid MDCs, I'm not sure about missing ones.

I'll see if it makes sense to make this behavior configurable.

**Comment by IvanPizhenko** [comment]
Missing one seems to be able to detected by checking `isIntegrityProtected` on the decryption stream result. So I assume that's something we already have. So my only question now is to how to detect missing MDC.

**Comment by tomholub** [comment]
I haven't checked the spec - but I'm not 100% sure that isIntegrityProtected and MDC is exactly the same functionality. I forgot it PGP has an integrity protected packet that is somehow different from a regular packet, and that being yet different from adding MDC or not - if you are testing with two messages, it is possible that one of them has both features and the other none.

(unless it is the same feature after all)

**Comment by vanitasvitae** [comment]
I did a quick check. MDCs are being correctly evaluated afaict.
Missing MDC packets result in PrematureEndOfStream errors, while tampered MDCs will result in PGPExceptions.
So there is no need to manually deal with MDC validation.

**Comment by tomholub** [comment]
I imagine this should work for our purposes - at least for now. @IvanPizhenko did you notice a message without MDC (or wrong MDC) get decrypted without throwing? If so then the message could be used as a test case to implement against to improve MDC handling.

**Comment by IvanPizhenko** [comment]
> I did a quick check. MDCs are being correctly evaluated afaict.
> Missing MDC packets result in PrematureEndOfStream errors, while tampered MDCs will result in PGPExceptions.
> So there is no need to manually deal with MDC validation.

Hmm - when I was trying to testing previous version of my decryption implementation, I was noticing strange `PrematureEndOfStream` errors. I was thinking it's a bug in test data, but that might indicate missing MDCs. I also have seen some other strange PGP exceptions for some inputs, maybe that could be MDC error?

Anyway - it would be far better if missing and incorrect MDCs could be detected somehow explicitly, so we do not rely on those PGP exception, with a bit cryptic error messages, which can potentially happen due to some other reasons than missing MDC. Is there a way to make exact conclusion - here MDC is missing and here is not - despite PGP exception?

**Comment by tomholub** [comment]
> Anyway - it would be far better if missing and incorrect MDCs could be detected somehow explicitly, so we do not rely on those PGP exception, with a bit cryptic error messages, which can potentially happen due to some other reasons than missing MDC

I agree with this - It would be great if PGPainless could throw an explicit `MdcException("MDC missing, message is unsafe to render")` or `MdcException("MDC does not match, message is unsafe to render")` where MDC exception could inherit from PGP exception for example. If not, then throw a PGPexception with a clear message that this is about MDC.

**Comment by IvanPizhenko** [comment]
> I imagine this should work for our purposes - at least for now. @IvanPizhenko did you notice a message without MDC (or wrong MDC) get decrypted without throwing? If so then the message could be used as a test case to implement against to improve MDC handling.

I've found one such test, at least by name it is declared to miss MDC, and there is no exception, it decrypts, but it sets `isIntegrityProtected` to `false`. Attaching here a file with test data.
[mdctest.txt](https://github.com/pgpainless/pgpainless/files/6382483/mdctest.txt)

@vanitasvitae please examine this

**Comment by vanitasvitae** [comment]
@IvanPizhenko how was this message created? The message contains a Symmetric Encrypted Data (SED) packet, which presents a security issue (enables efail) and should be avoided in favor of a Symmetrically Encrypted Integrity Protected Packet (SEIP).
It looks like PGPainless until now happily decrypts the message, which I shall fix now.
Furthermore I'm hearing that there is an issue with the generating software's RSA key generation.

**Comment by vanitasvitae** [comment]
I created #111 for further discussion about MDC related errors .)

**Comment by IvanPizhenko** [comment]
@vanitasvitae IDK how it was created, maybe @tomholub can tell more about that. It comes from the Flowcrypt browser extension tests, where it is one of tests that check MDC error detection.

**Comment by tomholub** [comment]
The message comes from some lousy OpenPGP software, from one of our client's correspondents.
