### ISSUE TITLE
Document all public interfaces

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#109]
One problem I constantly face with PGPainless which makes it much less painless (despite its name) is in fact missing documentation. I suggest to document at least *ALL* public classes and public class members with proper Javadoc.

**Comment by tomholub** [comment]
This will also allow you to export documentation from there to something like readthedocs - with well documented library, adoption will increase as well.

**Comment by vanitasvitae** [comment]
Yeah, I neglected documentation a bit recently, but I will give more care to it in the future.

**Comment by vanitasvitae** [comment]
Closing in favor of #28
