### ISSUE TITLE
Detect if actually used key/subkey requires passphrase

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#112]
I am creating "key protector" object like this:
 
```kotlin
fun decrypt ( ... , passphrase: Passphrase? ): ... {
  val protector = if (passphrase != null) {
    PasswordBasedSecretKeyRingProtector.forKey(pgpSecretKeyRing, passphrase)
  } else {
    UnprotectedKeysProtector()
  }
}
```
And later on I use it in the decryption process:
```kotlin
      val d = PGPainless.decryptAndOrVerify()
          .onInputStream(input)
          .decryptWith(protector, PGPSecretKeyRingCollection(listOf(pgpSecretKeyRing)))

      val decryptionStream = if (pgpPublicKeyRingCollection != null) {
        d.verifyWith(pgpPublicKeyRingCollection).ignoreMissingPublicKeys().build()
      } else {
        d.doNotVerify().build()
      }

      val output = ByteArrayOutputStream()
      decryptionStream.use { it.copyTo(output) }
```
So this function can potentially receive `null` as `passphrase` but key / subkey, requirted for decryption, itself may require passphrase. I want to detect this situation. Is is possible to do this with PGPainless?

**Comment by vanitasvitae** [comment]
You could use `PassphraseMapKeyRingProtector` which takes a `SecretKeyPassphraseProvider` as a missing-passphrase callback. That would be triggered if a missing passphrase is encountered (passphrase for the key is null).

**Comment by vanitasvitae** [comment]
You can, of course, always create your own implementation of `SecretKeyRingProtector` tailored to your needs (and upstream that if it makes sense ;P)

**Comment by vanitasvitae** [comment]
I modified `UnlockSecretKey` to check whether or not the selected secret key is encrypted, before trying to get a `PBESecretKeyDecryptor` object from the `SecretKeyRingProtector`.

That means that PGPainless will no longer ask for passphrases for unencrypted keys which were not explicitly marked as unencrypted in the SecretKeyRingProtector.
