### ISSUE TITLE
KeyRingInfo.getExpirationDate() is no longer available in the alpha10

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#113]
Was it removed intentionally? We need it.

**Comment by vanitasvitae** [comment]
It was replaced with `getPrimaryKeyExpirationDate()`. For subkeys, there is `getSubkeyExpirationDate(OpenPgpV4Fingerprint)`.

**Comment by tomholub** [comment]
Could there be a combined method? OpenPGP.js has methods for `getExpirationDate(use=ANY)`, `getExpirationDate(use=SIGNING)`, `getExpirationDate(use=ENCRYPTION)`.

Then it will evaluate combination of primary and subkeys holistically to figure out if the key can be used for that purpose as a whole. This would be very helpful for us.
