### ISSUE TITLE
Create `KeyRingInfo.getExpirationDate(use)`

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#114]
@tomholub wrote:
> OpenPGP.js has methods for getExpirationDate(use=ANY), getExpirationDate(use=SIGNING), getExpirationDate(use=ENCRYPTION).
> 
> Then it will evaluate combination of primary and subkeys holistically to figure out if the key can be used for that purpose as a whole. This would be very helpful for us.

I guess this method should check all available keys on the key ring and determine the nearest/farthest expiration date of any available key with the given usage.

**Comment by tomholub** [comment]
I think it should return the furthest date that the combination of primary key and its subkeys is still usable, for a certain usecase (signing, encryption, or any)

**Comment by tomholub** [comment]
In other words, what is the farthest date that I could still sign an item with this key (for example) without throwing an error. The library likely already has some functionality internally to make these decisions.

**Comment by vanitasvitae** [comment]
This has now been implemented :)
