### ISSUE TITLE
OpenPgpMetadata.isIntegrityProtected() is no longer there

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#115]
What is instead of it? I remember we were discussing that some exception should be there instead of it and there must be a way to suppress that exception. But I also think if you suppress exception you should have such flag to be able to check it.

**Comment by vanitasvitae** [comment]
PGPainless now requires data to be integrity protected.

Allowing unprotected data is not implemented. Is there a need for unprotected data?

**Comment by IvanPizhenko** [comment]
At least my current code uses it. I just upgraded to a new version and facing that my code no longer compiles. I will explore a new solution (exceptions) and let you know if that works good enough.

**Comment by vanitasvitae** [comment]
For reference:
The sequoia test suite shows [no implementation allowing unprotected data](https://tests.sequoia-pgp.org/#Message_structure) to be acceptable ("Downgrade to SED").

If not required, I would prefer not to add support for insecure data.

**Comment by IvanPizhenko** [comment]
Exception seems to work. So closing this one.
