### ISSUE TITLE
NPE in KeyRingInfo.getLastModified() 

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#125]
Please look at the following code. We've received the bug reports that indicate NPE in `getLastModified()`
It seems `getMostRecentSignature()` can return `null` as results. It would be nice if `PGPainless` will have `@Nullable` here (the best choice is to have that over the whole public methods (if needed)). It's very important for Kotlin usage( to prevent such a bug.)

```
/**
     * Return the date on which the key ring was last modified.
     * This date corresponds to the date of the last signature that was made on this key ring by the primary key.
     *
     * @return last modification date.
     */
    public Date getLastModified() {
        PGPSignature mostRecent = getMostRecentSignature();
        return mostRecent.getCreationTime();
    }

    private PGPSignature getMostRecentSignature() {
        Set<PGPSignature> allSignatures = new HashSet<>();
        if (mostRecentSelfSignature != null) allSignatures.add(mostRecentSelfSignature);
        if (revocationSelfSignature != null) allSignatures.add(revocationSelfSignature);
        allSignatures.addAll(mostRecentUserIdSignatures.values());
        allSignatures.addAll(mostRecentUserIdRevocations.values());
        allSignatures.addAll(mostRecentSubkeyBindings.values());
        allSignatures.addAll(mostRecentSubkeyRevocations.values());

        PGPSignature mostRecent = null;
        for (PGPSignature signature : allSignatures) {
            if (mostRecent == null || signature.getCreationTime().after(mostRecent.getCreationTime())) {
                mostRecent = signature;
            }
        }
        return mostRecent;
    }
```

P.S. And of course have warnings about `@Nullable`  in Java Docs will be super useful, like

`@return last modification date or null if ...`

**Comment by vanitasvitae** [comment]
Do you happen to have a test key available which caused this?

I can only imagine this to happen if there is no correct signature at all on the key, or if all signatures on the key were made in the future?

**Comment by DenBond7** [comment]
> Do you happen to have a test key available which caused this?

unfortunately, I don't have such a key. We received anonymous error feedback(that is making automatically) that we collect from users

**Comment by vanitasvitae** [comment]
I see. I will try to make the method NPE-proof nonetheless :)

**Comment by vanitasvitae** [comment]
The method should now no longer throw NPEs. If no signatures are found, the method falls back to the latest key-creation date.

**Comment by DenBond7** [comment]
Thank you!
