### ISSUE TITLE
bringing more functionality into PGPainless

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#13]
As per email conversation, I'd like to open a discussion between @wiktor-k and @vanitasvitae on some of the things we'd love to see in this library that we'd like to sponsor. The first things that come to mind are:
 - detailed info about keys
 - key revocation functionality
 - ecc, in particular Curve25519 (for key generation, encryption, decryption, signing, verification) 
 - compatibility tests - core: we have accumulated some test cases from our own PGP apps (particularly in https://github.com/FlowCrypt/flowcrypt-browser ) that will be great to borrow the test vectors and test them also here in this library. It will probably uncover some blind spots.
 - compatibility tests - extended: I'd like to look at test cases from OpenPGP.js (which we heavily rely on, on some platforms), take the more interesting ones and craft similar tests in this library, again to ensure wide compatibility
 - once we are getting closer to having the above done, I'll arrange a security audit to uncover security issues

I'll let Wiktor give you more details on the particular usecases that we expect, and then you two can discuss it further, independently of me.

I'm very much looking forward to this, the Java space badly needs usable OpenPGP tooling :+1:

// edit: for Wiktor: if there is any functionality that we have already independently implemented (key info comes to mind), you are free to copy code samples and paste them here, it may save a bit of time

**Comment by wiktor-k** [comment]
> ecc, in particular Curve25519 (for key generation, encryption, decryption, signing, verification)

I believe OpenKeychain had 25519 included in their fork so this could be good starting point.

> compatibility tests - core: we have accumulated some test cases from our own PGP apps (particularly in https://github.com/FlowCrypt/flowcrypt-browser ) that will be great to borrow the test vectors and test them also here in this library. It will probably uncover some blind spots.

This is important as basically there are two endpoints that need to talk to each other. FTR there is a broader project to test multiple OpenPGP implementations at https://tests.sequoia-pgp.org/ This utilizes [stateless OpenPGP CLI](https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-02) but this is probably out of scope for now :)

**Comment by tomholub** [comment]
> FTR there is a broader project to test multiple OpenPGP implementations at https://tests.sequoia-pgp.org/ This utilizes stateless OpenPGP CLI but this is probably out of scope for now :)

:+1: This would I think be a great thing to do following the initial needed functionality: work on getting the implementation onto these tests, and then improving compatibility based on these tests.

**Comment by tomholub** [comment]
> I believe OpenKeychain had 25519 included in their fork so this could be good starting point.

In their fork of BouncyCastle? I do see their license is permissive so as long as we are careful to give credits where due, this would indeed be good. https://github.com/open-keychain/bouncycastle/blob/openkeychain-master-old/LICENSE.html

**Comment by wiktor-k** [comment]
> In their fork of BouncyCastle?

Yeah, I wonder why this wasn't upstreamed, I'll ask the author.

**Comment by vanitasvitae** [comment]
> detailed info about keys

Could you elaborate what exactly you mean by this? BC already has a lot of methods to get information about keys. What exactly is missing?

Maybe @wiktor-k could create a patch with an interface with methods that would be needed? Alternatively just create a new ticket with more information :)

**Comment by tomholub** [comment]
I've made separate issues with more information to make them actionable - I'll go ahead and close this one and we can continue conversation there as needed.
