### ISSUE TITLE
API for key editing

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#14]
Currently stuff like additional user-ids can only be set on a key during key creation.

It would be more logical to have a key editing API that allows for addition/removal of user-ids and subkeys, as well as modification of other key attributes like extension/revocation of certifications.

The API *could* roughly resemble [GnuPGs edit-key command](https://www.gnupg.org/gph/en/manual/r899.html).

To keep track of this, here is a list of features that need to be implemented:

* [x] add user-ids to keys
* [x] delete user-ids from keys
* [x] extend expiry dates
* [x] add subkeys
* [x] delete subkeys
* [x] revoke subkeys
* [x] change passphrases of keys (whole ring + subkeys)

**Comment by vanitasvitae** [comment]
The API should consist of actions that can be performed on a PGPSecretKeyRing.

Below is a sketch of how the API could look like:
```
PGPainless.modifyKeyRing(secretKeyRing)
    ...
    // This could be a shortcut method for adding a simple string user-id.
    // Later we could also add methods to add information like name, email, comments using a builder (see https://tools.ietf.org/html/rfc2822)
    .addUserId("alice@wonderland.lit")

    .deleteUserId("alice@literature.club")

    .setExpiryDate(newExpiryDate|LocalDate)

    .addSubKey(keySpec|keyPair)

    .deleteSubKey(fingerprint|keyId)

    .revokeSubKey(fingerprint|keyId)

    .changePassphrase("old", "new")
    // as @tomholub pointed out, subkeys might come with separate passphrases, so we might want to account for this by 
    // allowing the user to pass in a map of key-ids and associated passphrases
    .changePassphrase(oldMap, newMap)
```

**Comment by vanitasvitae** [comment]
Progress is tracked in https://github.com/pgpainless/pgpainless/tree/keyEditing

**Comment by tomholub** [comment]
Agree, this would be useful. I don't know if your existing APIs cover this, but changing pass phrase comes to mind.

In OpenPGP.js this is achieved with something like `key.decrypt(List<String>)` and `key.encrypt(String)`. The reason the decrypt takes a list is that each subkey may be (unfortunately..) actually encrypted with a different pass phrase. This is not probably a scenario you want to support when encrypting a key, but for compatibility, one has to support it when decrypting. The implementation then tries to decrypt each key packet with each pass phrase until all are successful.

The decrypting and encrypting is particularly sensitive to get right - the API should be designed to make it an atomic operation. It would be a security problem if for example one subkey got decrypted, another one failed let's say with a thrown exception, but the original object remained altered with one subkey still encrypted and one decrypted.

**Comment by vanitasvitae** [comment]
Ah yes, passphrase changes are a use-case as well.
Thanks for pointing out the issue of multiple passphrases per key-ring :+1:

**Comment by vanitasvitae** [comment]
I just did a first successful test of adding user-ids to a key using the new edit key API I'm working on.

I'll probably replace the existing "add user-id during key creation" code to this API.

**Comment by tomholub** [comment]
:+1: sounds ok to me

@wiktor-k any downside to having the initial user have slightly older signature than additional users? I cannot come up with any.

**Comment by vanitasvitae** [comment]
To be clear, the code that added the user-id "during creation" really just generated the key and added the user-id afterwards.
I did it that way as I'm not aware of a way to "really" add the user-id during creation so that it is covered by the same signature.

See https://github.com/bcgit/bc-java/issues/801

**Comment by tomholub** [comment]
lgtm - thanks for context

**Comment by vanitasvitae** [comment]
Changing passphrase of the whole keyring now works. Changing the passphrase of separate subkeys *should* work, but is not yet tested.

All in all I obviously need some more tests for the new API, but I'm making some progress :)

**Comment by wiktor-k** [comment]
>  any downside to having the initial user have slightly older signature than additional users? I cannot come up with any.

There are just a few minor reasons: privacy - you can see which user id was created in which reason. Also remember that if the new User ID has different preferences (algos etc.) they'd usually take precedence (newer creation date). But this doesn't come often and the effects are miniature so I guess we could just ignore it :)

@vanitasvitae, remember to have a separate test case for changing password to empty password (no password, no key protection). I think I had a different objects with password-protected and not-protected scenarios :)

Thanks for your work!

**Comment by vanitasvitae** [comment]
Changing key passphrases now has some baseline tests.
Funny thing: If you have a key with an empty passphrase (aka unprotected key) and try to decrypt it using a PBESecretKeyDecryptor that is based on a passphrase, say "password", bouncycastle will happily "decrypt" the key. 

This caused some confusion during testing, but I wrote some DSL to catch this in my tests. :D

**Comment by vanitasvitae** [comment]
I'm just working on implementing deleting secret keys from a keyring.
I wonder: Should it be possible to delete the primary secret key from a secret key ring?
I know that this might make sense in some scenarios (eg. store the primary key somewhere safe and use subkeys instead.
However, BCs implementation requires the primary key to be present (see [this constructor](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKeyRing.java#L74) which calls [checkKeys](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKeyRing.java#L46-L52) which requires the primary key to be present).

For now I guess it makes sense to prevent the user from deleting the primary key?

**Comment by vanitasvitae** [comment]
Deleting user-ids from keys is now supported as well, along with deleting subKeys as a whole.

**Comment by vanitasvitae** [comment]
@wiktor-k About adding sub-keys: Would you like to be able to pass finished keys to the method or would it be enough to just pass it a KeySpec object from which the subkey is generated on the fly? Or maybe both?

**Comment by vanitasvitae** [comment]
I'm currently hitting a bug while trying to implement adding subkeys: https://github.com/pgpainless/pgpainless/issues/20
Any input on this is appreciated.

**Comment by tomholub** [comment]
I don't think we currently have a need to adding finished subkeys onto a key.

It would be enough to have a way to have more subkeys generated. Even that is not an urgent need, but will definitely eventually be useful.

**Comment by vanitasvitae** [comment]
Adding subkeys is implemented with https://github.com/pgpainless/pgpainless/commit/b4967db1a2a0937f3b25707c2ab15c5022a722ce :)

**Comment by vanitasvitae** [comment]
Revoking subkeys is now implemented as well. I also switched over to the JUnit Jupiter API for testing and released PGPainless 0.2.0-alpha2 to maven central :)

Edit: Whoops, I just noticed that I only implemented revoking subkeys using their fingerprint, not their key-id. Fixing that is easy though, so expect another release soon :D
Edit2: Fixed in https://github.com/pgpainless/pgpainless/commit/4dd2b2f71a5a8c103ff26ddf34bc646f83648c2c

**Comment by vanitasvitae** [comment]
It is now also possible to create detached key revocation certificates. Although I'd say the API for this is pretty straight forward already, I think there are some things we can improve upon still.

```
        PGPSecretKeyRing secretKeys = TestKeys.getCryptieSecretKeyRing();
        OpenPgpV4Fingerprint fingerprint = new OpenPgpV4Fingerprint(secretKeys);
        SecretKeyRingProtector protector = PasswordBasedSecretKeyRingProtector.forKey(secretKeys, Passphrase.fromPassword("password123"));

        PGPSignature revocationCertificate = PGPainless.modifyKeyRing(secretKeys)
                .createRevocationCertificate(fingerprint, protector, RevocationAttributes.createKeyRevocation()
                        .withReason(RevocationAttributes.Reason.KEY_RETIRED)
                        .withDescription("Key no longer used."));
--------------------------------------------------------------------------------------------------
# off=0 ctb=88 tag=2 hlen=2 plen=139
:signature packet: algo 19, keyid F49AAA6B067BAB28
	version 4, created 1605869397, md5len 0, sigclass 0x20
	digest algo 10, begin of digest 01 14
	hashed subpkt 2 len 4 (sig created 2020-11-20)
	hashed subpkt 33 len 21 (issuer fpr v4 A395D3BA58CA3FA0DE8F2991F49AAA6B067BAB28)
	hashed subpkt 29 len 20 (revocation reason 0x03 (Key no longer used.))
	subpkt 16 len 8 (issuer key ID F49AAA6B067BAB28)
	data: [250 bits]
	data: [256 bits]

```
:partying_face:

**Comment by vanitasvitae** [comment]
Regarding editing expiry dates:
@wiktor-k created a pull request that allows setting the expiry date for the primary key and I'm currently thinking about ways to allow for arbitrary subkey expiry date editing.

Ideally I want to allow the user to change the expiry date of any key and still preserve the subpackets on the last signature.
As far as I can tell GnuPG does the same (when you edit the key expiry date, it not only creates new signatures for all user-ids (might be worth to allow modifying this behavior as well at some distant point), but it also preserves all subpackets of the previous signature (preferred algos, notations etc).
I fear I have to propose some changes to BC, as the API for editing subpacketvectors is not very suitable for this.
Maybe a subpacketVectorBuilder would be what is needed?

**Comment by vanitasvitae** [comment]
I created https://github.com/bcgit/bc-java/pull/848 upstream. Lets see if this gets accepted :)

**Comment by vanitasvitae** [comment]
My PR was merged, but modified. Yet a future release of BC should now be capable of preserving subpackets when altering expiration dates :tada:

**Comment by vanitasvitae** [comment]
Bouncycastle 1.68 [has been released](https://www.bouncycastle.org/releasenotes.html) and now supports modification of existing subpacket vectors! Now we can bump the BC dependency and implement changing key expiration dates :+1:

**Comment by vanitasvitae** [comment]
Regarding changing key expiration dates:
Since a key can have more than one signature that contains an expiration date, it probably makes sense to reflect this in the API.
That means we should have a general method that extends the expiration date of all signatures made by ourself, as well as a more fine grained method that allows to change the expiration date of single signatures (eg. to extend the expiration date of a single user-id or subkey only).

This obviously makes the API more complex, so while we should allow it, we should promote the more general method that extends all signatures to the user.

**Comment by tomholub** [comment]
On my end I think it may be ok to skip the more complex API for now - we don't have any usecase for it, I think. But I understand that others may, so you should implement it if you think it will be useful.

**Comment by vanitasvitae** [comment]
@tomholub alright, thanks for the hint, I guess for now I will stick with a less complex API then :)

**Comment by IvanPizhenko** [comment]
@vanitasvitae is there already a way to add user id to the key?

**Comment by tomholub** [comment]
I haven't tested it, but possibly

```
PGPainless.modifyKeyRing(secretKeyRing)
    .addUserId("alice@wonderland.lit")
    .deleteUserId("alice@literature.club")
    .done()
```

(Did you need it for the EAP mock? If yes, please add a general method to the `Pgp` class like `Pgp.setKeyUids(..., uids: List): Pair` similar to the other methods that we use to update keys. Then we can later copy it to EKM)

**Comment by IvanPizhenko** [comment]
yes, exactly.
ok, will add.

**Comment by pragmaxim** [comment]
Hi, I noticed that a publicKey generated by gnuPG (2048, just default settings) without ExpirationDate set, cannot be used for encryption : 
```
        PGPainless
          .encryptAndOrSign()
          .onOutputStream(outputStream)
          .withOptions(
            ProducerOptions
              .encrypt(
                EncryptionOptions
                  .encryptCommunications()
                  .addRecipient(PGPainless.readKeyRing.publicKeyRing(publicKey))
                  .addPassphrase(Passphrase.fromPassword(passphrase))
              )
              .setAsciiArmor(true)
          )
```
Due to  : 
```
        Suppressed: org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key 28757F5AD7A4DDB70891C4AFE95E3C6299AAA603 does not have a valid/acceptable signature to derive an expiration date from.                       
                at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:298)                                                                                                                              
                at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:265)                                                                                                                                
                at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:253)                                                                                                                                
```

Is there a workaround of that?

**Comment by vanitasvitae** [comment]
Also note, that `.addPassphrase()` is used to add a passphrase as an additional option to decrypt the message using the passphrase, not for unlocking the secret key (which is not needed for the encryption without signing).
