### ISSUE TITLE
Generate key not response

### ISSUE THREAD

**Issue by Xing1P** [pgpainless/pgpainless#146]
PGPSecretKeyRing pgpSecretKeys = PGPainless.generateKeyRing().simpleRsaKeyRing(jid, RsaLength._4096);

- pgpainless-core:0.2.0
- Generate key not response
- Test in Phone Model Oppo F9
- Android 10 
*Test in oneplus 7 pro Android 11 key can generate success.

**Comment by vanitasvitae** [comment]
What do you mean by "no response"?
Does your app crash? Does it display the "this app is not responding" dialog?
Does it simply hang indefinitely?

It sounds like you are generating the key on Androids UI Thread. You should do it in a background thread.

**Comment by Xing1P** [comment]
I'm generate key in android worker. then is not reach success.
My code:
`public class GeneratePubKeyWorker extends Worker {
    private static final String TAG = GeneratePubKeyWorker.class.getSimpleName();

    public GeneratePubKeyWorker(@NonNull Context context, @NonNull WorkerParameters workerParams) {
        super(context, workerParams);
    }

    @NonNull
    @Override
    public Result doWork() {
        LogManager.d(TAG, "doWork");
        try {
            PGPSecretKeyRing pgpSecretKeys = PGPainless.generateKeyRing().simpleRsaKeyRing("123456", RsaLength._4096);
            LogManager.d("Never-Reach-Me","yes");
            return Result.success();
        } catch (Exception ex) {
            LogManager.d("Never-Reach-Me-Too","yes");
            ex.printStackTrace();
            return Result.success();
        }
    }
}`

**Comment by vanitasvitae** [comment]
Is the oppo a weaker device? I don't have access to such a device, so unfortunately I cannot check this myself.

I know that generation of RSA keys is quite a resource hungry task. Its likely that the device is simply running out of entropy, so that the key generation takes a HUGE amount of time. Maybe try ECC keys instead?

**Comment by Xing1P** [comment]
Yes ECC very faster than RSA. generate RSA key very delay for oppo or weaker phone.
