### ISSUE TITLE
discussion - new vs old packet format

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#162]
> Furthermore some packets in your message were using the [new packet lengths format](https://datatracker.ietf.org/doc/html/rfc4880#section-4.2.2) (indicated by `new CTB` in the dumper) where pgpainless/BC uses the [old format](https://datatracker.ietf.org/doc/html/rfc4880#section-4.2.1) (old CTB). It would surprise me if this was the cause of the issue though.

_Originally posted by @vanitasvitae in https://github.com/pgpainless/pgpainless/issues/160#issuecomment-890405862_

I'm posting this here in case it may be preferable to use the new format.

**Comment by vanitasvitae** [comment]
Unfortunately whether or not the new format is used is hard coded inside of BC (eg. [here](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/java/org/bouncycastle/bcpg/PublicKeyEncSessionPacket.java#L125))

```
out.writePacket(tag: PUBLIC_KEY_ENC_SESSION , data: bOut.toByteArray(), oldFormat: true);
```

**Comment by tomholub** [comment]
For the long term, it will be very good to have this be configurable by the BC api.

I know BC can be slow to accept fixes, but it will be worthwhile to submit this functionality to BC, so that we have more flexibility in PGPainless.

**Comment by vanitasvitae** [comment]
I'm not sure, how to elegantly implement such an API though. Add a static OLD_PACKET_FORMAT boolean to all packet classes?

Currently each packet "decides" for itself, whether or not to use the old/new format.

Maybe BC devs can be convinced to have a "switch day" where a new release completely switches over to the new format when encoding packets?

**Comment by tomholub** [comment]
I'm not too familiar with BC, so I'm not sure. Does it have any global config?

> Maybe BC devs can be convinced to have a "switch day" where a new release completely switches over to the new format when encoding packets?

Maybe. Failing that, a configurable switch in code instead of a switch day - somehow.

Or a fork, again :-/

**Comment by vanitasvitae** [comment]
It looks like BC will switch to the new packet format exclusively at some point (see https://github.com/deviantdev/bc-java/commit/94e8b9c5924c534fce17a5f19c18a6fa2507ad7d and https://github.com/deviantdev/bc-java/commit/2d7814a5f15ee2bc7023345630a50395ef2a2683).
