### ISSUE TITLE
fingerprint of signing key in signed messages

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#163]
> Lastly I noticed, that FlowCrypt was adding the fingerprint of the issuer key to the signature. This could be added inside of PGPainless, but again, I doubt that this is the cause of the issue.

_Originally posted by @vanitasvitae in https://github.com/pgpainless/pgpainless/issues/160#issuecomment-890405862_

Is that actually possible to include a full fingerprint in signed messages? I was only aware of LongID shared this way. Is there a new format that allows sharing fingerprint?

What exactly does PGPainless do and what exactly does OpenPGP.js do?

Thank you!

**Comment by vanitasvitae** [comment]
Apparently there are the following methods of denoting which key made a particular signature:
* Issuer Key-ID: the short key-id of a subkey (eg. `Issuer: 0935E20FDC99D986`). MUST NOT be used for V5+ keys.
* Issuer Fingerprint: The long representation of a key identifier. This is versioned, so there are different representations possible:
  * V4 fingerprint: 20 octets of the keys fingerprint (eg. `Issuer Fingerprint: 8DE64CAD1758FC194560CF590935E20FDC99D986`)
  * V5 fingerprint: 32 octets of the keys fingerprint

PGPainless (or rather BC) by default only includes an issuer key-id packet, but it is possible to add a V4 issuer fingerprint packet as well. OpenPGP.js apparently does this by default. Maybe we should upstream a change to BC to include issuer fingerprint by default?

**Comment by tomholub** [comment]
Excellent. Either we can ourselves additionally add a full fingerprint by default, or we can upstream this to BC (or both, until BC merges).

Are we able to also retrieve full fingerprint from signed message?

I didn't know this, excited that it's possible to get fingerprint out of newer format messages. We still keep getting it by longid in all of our apps, even if there is in fact fingerprint available, due to my ignorance.

**Comment by vanitasvitae** [comment]
PGPainless will now include the issuer-fingerprint into message signatures by default.

If you want to retrieve a fingerprint from a signature, you can use `SignatureSubpacketsUtil.getIssuerFingerprintAsOpenPgpV4Fingerprint(signature)`.

**Comment by tomholub** [comment]
> SignatureSubpacketsUtil.getIssuerFingerprintAsOpenPgpV4Fingerprint(signature)

Does this return a null, or throw, when it's not available?
What if it's a v5 finerprint?

**Comment by vanitasvitae** [comment]
If no v4 issuer fp is present it will return null.
Good call with v5 fingerprints! I just changed the code to return null instead of throwing.

**Comment by vanitasvitae** [comment]
At some point I should start thinking about support for v5 keys inside of pgpainless. Once this is implemented in BC having simultaneous support for different versions will become quite a task :D

**Comment by tomholub** [comment]
> If no v4 issuer fp is present it will return null.
> Good call with v5 fingerprints! I just changed the code to return null instead of throwing.

It would be better to have a method that works the same regardless if it's V5 or V4 fingerprint. This level of detail should not be exposed to PGPainless user, I think.

**Comment by vanitasvitae** [comment]
The library consumer probably wants to use `OpenPgpMetadata.getVerifiedSignatures()` anyways.
Edit: The result is a Map<SubkeyIdentifier, PGPSignature>, where the key contains the fingerprint of the signing key, regardless of whether it was included in the signature or not. However, the fingerprint is expected to be v4 here as well, so this needs to change at some point.

SubkeyIdentifier exposes both the v4 fingerprint of the primary key of the signing key, as well as the fingerprint of the signing subkey itself.
And via `subkeyIdentifier.getPrimaryKeyId()/.getSubkeyId()` you can access the keys ids if needed.

**Comment by tomholub** [comment]
> The library consumer probably wants to use OpenPgpMetadata.getVerifiedSignatures() anyways.
Edit: The result is a Map<SubkeyIdentifier, PGPSignature>, where the key contains the fingerprint of the signing key, regardless of whether it was included in the signature or not.

What will happen here if the signature did not include full fingerprint, and instead included just a longid?

**Comment by vanitasvitae** [comment]
In this case we use the longid to get the right signing key, verify the signature and then retrieve the fingerprint from the key itself.

**Comment by vanitasvitae** [comment]
This obviously only works if the user provided the right key to verify the signature.

**Comment by vanitasvitae** [comment]
In theory, this should also work with signatures that did not include any hints to the signing key at all (eg. wildcard key-ids), but in practice PGPainless might not be able to figure this out properly. This is because we first verify the signing key integrity, before we verify the signature itself. However, for wildcard key-ids we need to do it the other way round (first try every available key to figure out which one was actually used to create the sig, then check if it was elligible).

At some point we should fix this as well, but for the time being I guess wildcard sigs are rare enough to be ignored for now.
