### ISSUE TITLE
is keyring usable for encryption?

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#165]
I'd like to find out if a particular OpenPGP key can be used for encryption right now.

With OpenPGP.js we do something like `key.getEncryptionPacket()` and if it returns the packet, we consider it usable.

Fundamentally, I'd like to ask a question "if I used this key right now to encrypt something, would it succeed or fail?". 

Is there a way to find out?

**Comment by vanitasvitae** [comment]
You can use `KeyRingInfo.getEncryptionSubkeys(purpose)` to get all keys capable of encryption. 
The list should only contain keys which are usable.

**Comment by tomholub** [comment]
Excellent.
