### ISSUE TITLE
Question. Do we have a method to extract text from "PGP SIGNED MESSAGE"?

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#172]
Let's imagine that we have the following

```pgp
-----BEGIN PGP SIGNED MESSAGE-----
Hash: [Hash algorithm]
[Human Readable Message Body]
-----BEGIN PGP SIGNATURE-----
[Signature]
-----END PGP SIGNATURE-----
```

Do we have a method to extract `Human Readable Message Body`?

**Comment by vanitasvitae** [comment]
Yes, that kind of message is using the "Cleartext Signature Framework".

You can use `PGPainless.verifyCleartextSignedMessage()` to process such messages :)

**Comment by DenBond7** [comment]
Thank you! 

I can do it in the following way

```java
InMemoryMultiPassStrategy multiPassStrategy = MultiPassStrategy.keepMessageInMemory();
PGPSignatureList signatures = ClearsignedMessageUtil.detachSignaturesFromInbandClearsignedMessage(new ByteArrayInputStream(MESSAGE_SIGNED), multiPassStrategy.getMessageOutputStream());
assertArrayEquals(MESSAGE_BODY, multiPassStrategy.getBytes());
```

**Comment by vanitasvitae** [comment]
I would recommend, you do
```
        InMemoryMultiPassStrategy multiPassStrategy = MultiPassStrategy.keepMessageInMemory();
        CleartextSignatureProcessor processor = PGPainless.verifyCleartextSignedMessage()
                .onInputStream(new ByteArrayInputStream(MESSAGE_SIGNED))
                .withStrategy(multiPassStrategy)
                .withOptions(options);

        PGPSignature signature = processor.process();
```
which will process the message and especially verify correctness of the signatures (which your code snippet does not!).
The message body can be accessed by `multiPassStrategy.getBytes()/.getOutputStream()`
I think I will rework this API to make it return some object from which the message body can be accessed intuitively, regardless of which strategy is used.

**Comment by DenBond7** [comment]
I see. For now, I just need to extract only text(without signature verification). Currently, Flowcrypt for Android doesn't support signatures. We have issues for that https://github.com/FlowCrypt/flowcrypt-android/issues/1096 and https://github.com/FlowCrypt/flowcrypt-android/issues/1097. We are in the migration process.

**Comment by vanitasvitae** [comment]
I see.
Feel free to let me know, what information about signatures you'd like to have accessible from PGPainless' API once you are migrating :)

**Comment by vanitasvitae** [comment]
Oh, also let me know if you need support to create cleartext signed messages.

**Comment by DenBond7** [comment]
> Oh, also let me know if you need support to create cleartext signed messages.

@tomholub What do you think about that?

**Comment by tomholub** [comment]
Definitely, we'll likely need cleartext signing. Either way that's sensible to have that as a part of pgp library, both inline (text + signature) or pgp/mime (standalone signature).
