### ISSUE TITLE
Change passphrase. Automatically change to a secure method if the key already uses insecure method 

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#178]
ref https://github.com/FlowCrypt/flowcrypt-android/pull/1449
> when changing/settings pass phrase, we should always use the more secure mechanism regardless of what the key already has (if that makes sense)

ref https://github.com/FlowCrypt/flowcrypt-android/issues/1450

> Best would be if that was the default - if the key already uses insecure method and we change pass phrase, it should automatically change to a secure method.

Some details can be found here #176

**Comment by vanitasvitae** [comment]
I just pushed a fix utility class that repairs affected secret keys.
Until BC fixes its default behavior which causes this issue, we could think about adding the class as a workaround to either the key ring reader classes or maybe only at the changePassphase code segment?

Edit: [Link](https://github.com/pgpainless/pgpainless/blob/c851457ef8c727a3abb05b5078f97ed1fe4c2db9/pgpainless-core/src/main/java/org/pgpainless/key/protection/fixes/S2KUsageFix.java)

**Comment by DenBond7** [comment]
I've checked your code and it works great. It fixes the following issue. Just need to call it manually.

I use the following code

```kotlin
  private fun changeKeyPassphrase(
    key: PGPSecretKeyRing,
    oldPassphrase: Passphrase,
    newPassphrase: Passphrase
  ): PGPSecretKeyRing {
    val hasKeyWithUsageCheckSum = key.any { it.s2KUsage == SecretKeyPacket.USAGE_CHECKSUM }
    val keyRing = if (hasKeyWithUsageCheckSum) {
      S2KUsageFix.replaceUsageChecksumWithUsageSha1(
        key,
        PasswordBasedSecretKeyRingProtector.forKey(key, oldPassphrase)
      )
    } else {
      key
    }
   return PGPainless.modifyKeyRing(keyRing)
      .changePassphraseFromOldPassphrase(oldPassphrase)
      .withSecureDefaultSettings()
      .toNewPassphrase(newPassphrase)
      .done()
  }
```

> we could think about adding the class as a workaround to either the key ring reader classes or maybe only at the changePassphase code segment?

It would be great to cover this issue automatically by the lib. In that case, all devs will receive fixing without manual iterations.
As for me I would add fixing in the `changePassphase` code segment. It will be much clearer. We try to modify some key -> found less secure point -> fix it -> save a key with fixed things.

**Comment by vanitasvitae** [comment]
Great code example!
I will include something similar, although Java-esque in PGPainless :D

**Comment by vanitasvitae** [comment]
I applied a variant of your suggested change as https://github.com/pgpainless/pgpainless/commit/194e4d7631fec6c53b887c532666aaa8b6365477

**Comment by DenBond7** [comment]
Should we wait for a new release soon with this fix? I don't hurry up you, I can create a snapshot for us. Just wanted to clarify. Some of our users are waiting for this fix.

**Comment by vanitasvitae** [comment]
Let me create a quick release then :)

**Comment by vanitasvitae** [comment]
Hm, I'm having troubles with maven central.
I will try again in an hour or so, but I cannot promise that you will have a release by tomorrow :/

**Comment by DenBond7** [comment]
Thank you for trying. Don't worry. Please let me know when it will happen.

**Comment by vanitasvitae** [comment]
Fixed it (I hope :crossed_fingers:)
0.2.12 should be available soon on maven central.

**Comment by DenBond7** [comment]
Thank you! I've already applied a new version. Works great!
