### ISSUE TITLE
Can't read secret key in the binary format

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#179]
```kotlin
val secretKeyRing = PGPainless.readKeyRing().secretKeyRing(bytes)
```
returns `null`, where `bytes` contains following content (unzip before use, had to zip because GitHub did not accept it as is):
[privateKey.bin.zip](https://github.com/pgpainless/pgpainless/files/7131781/privateKey.bin.zip)

Looking a bit for what is happening inside, it creates `ArmoredInputStream` to read this, which is wrong.

So can we have an option to tell it explicitly that we are going to read binary / armored or it should try to detect, which it does now, but fails to do it correctly.

**Comment by Jerbell** [comment]
Why is `ArmoredInputStream` incorrect?
Isn't this what we do in `Pgp::modifySecretKey`?

**Comment by DenBond7** [comment]
@IvanPizhenko Are you sure you have a valid key? I receive `gpg: no valid OpenPGP data found` for your key.

```cmd
denbond7@WorkPC:~/Documents$ gpg --list-packets privateKey.bin
gpg: no valid OpenPGP data found.
gpg: processing message failed: Unknown system error
denbond7@WorkPC:~/Documents$ gpg --list-packets single_prv_key_binary.key 
# off=0 ctb=94 tag=5 hlen=2 plen=134
:secret key packet:
	version 4, algo 22, created 1617896902, expires 0
	pkey[0]: [80 bits] ed25519 (1.3.6.1.4.1.11591.15.1)
	pkey[1]: [263 bits]
	iter+salt S2K, algo: 9, SHA1 protection, hash: 2, salt: 9A99A103090D0AF0
	protect count: 65536 (96)
	protect IV:  4d 09 8d b8 88 5e 90 22 16 08 1c 56 6f 4b 9b ab
	skey[2]: [v4 protected]
	keyid: 7A629E78AB512B23
# off=136 ctb=b4 tag=13 hlen=2 plen=19
:user ID packet: "user@pgpainless.key"
# off=157 ctb=88 tag=2 hlen=2 plen=120
:signature packet: algo 22, keyid 7A629E78AB512B23
	version 4, created 1617896903, md5len 0, sigclass 0x13
	digest algo 10, begin of digest 13 84
	hashed subpkt 2 len 4 (sig created 2021-04-08)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 22 len 4 (pref-zip-algos: 2 3 1 0)
	hashed subpkt 11 len 3 (pref-sym-algos: 9 8 7)
	hashed subpkt 21 len 4 (pref-hash-algos: 10 9 8 11)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 25 len 1 (primary user ID)
	subpkt 16 len 8 (issuer key ID 7A629E78AB512B23)
	data: [255 bits]
	data: [256 bits]
# off=279 ctb=9c tag=7 hlen=2 plen=139
:secret sub key packet:
	version 4, algo 18, created 1617896903, expires 0
	pkey[0]: [88 bits] cv25519 (1.3.6.1.4.1.3029.1.5.1)
	pkey[1]: [263 bits]
	pkey[2]: [32 bits]
	iter+salt S2K, algo: 9, SHA1 protection, hash: 2, salt: 9A99A103090D0AF0
	protect count: 65536 (96)
	protect IV:  06 1d 70 f7 6e 12 97 82 6a e6 b7 23 cf 9f 55 a6
	skey[3]: [v4 protected]
	keyid: D28DB33179A6BEB7
# off=420 ctb=88 tag=2 hlen=2 plen=117
:signature packet: algo 22, keyid 7A629E78AB512B23
	version 4, created 1617896903, md5len 0, sigclass 0x18
	digest algo 10, begin of digest df f5
	hashed subpkt 2 len 4 (sig created 2021-04-08)
	hashed subpkt 27 len 1 (key flags: 0C)
	hashed subpkt 22 len 4 (pref-zip-algos: 2 3 1 0)
	hashed subpkt 11 len 3 (pref-sym-algos: 9 8 7)
	hashed subpkt 21 len 4 (pref-hash-algos: 10 9 8 11)
	hashed subpkt 30 len 1 (features: 01)
	subpkt 16 len 8 (issuer key ID 7A629E78AB512B23)
	data: [255 bits]
	data: [255 bits]
denbond7@WorkPC:~/Documents$ 
```

**Comment by DenBond7** [comment]
Btw, this [test](https://github.com/pgpainless/pgpainless/blob/447c08b446a785da1ff1872c47ad2298cd283d3d/pgpainless-core/src/test/java/org/pgpainless/key/parsing/KeyRingReaderTest.java#L252) covers a lot of cases.

**Comment by IvanPizhenko** [comment]
That's what I've got from the EKM database. Maybe it is additionally encrypted? Continue discussion in the original EKM issue.

**Comment by vanitasvitae** [comment]
Hm, I can't manage to process this key with conventional software. Neither GnuPG nor Sequoia-PGP recognize the format, so I'm clueless. Comparing a hex dump to other key dumps and to the standard didn't yield any results either.

It would be interesting to know what kind of key this is.

**Comment by IvanPizhenko** [comment]
It may be encrypted, that's why it is not recognized.

**Comment by vanitasvitae** [comment]
But it is not encrypted using an OpenPGP encryption scheme, is it?
Otherwise I'd OpenPGP packet dumper utils like `gpg --list-packets`, `sq inspect` or `sq packet dump` to recognize that this is an encrypted object.

**Comment by IvanPizhenko** [comment]
Yes, it is likely encrypted somehow differently.

**Comment by vanitasvitae** [comment]
Okay, I'll close this then for now.
Feel free to reopen :)

**Comment by Jerbell** [comment]
The private keys are encrypted in EKM - sorry, should have mentioned this yesterday.  When db encryption is enabled you can't just copy keys from the DB.
