### ISSUE TITLE
How to generate new key with signature class 0x10?

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#180]
Related to #177 
I'd like to generate a key for use in the unit test.
But by default key is generated with signature type 0x13.
```kotlin
    fun generatePgpKey() {
        val kr = PGPainless.generateKeyRing().simpleRsaKeyRing("John Smith <jsmith@mock.org>", RsaLength._4096)
        val armored = PGPainless.asciiArmor(kr)
        File(getenv("HOME") + "/Downloads/kr.txt").writeText(armored)
    }
```
Then
```shell
gpg --dearmor ~/Downloads/kr.txt
gpg --list-packets ~/Downloads/kr.txt.gpg
```
prints:
```
# off=0 ctb=95 tag=5 hlen=3 plen=1816
:secret key packet:
        version 4, algo 1, created 1631264750, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        skey[2]: [4094 bits]
        skey[3]: [2048 bits]
        skey[4]: [2048 bits]
        skey[5]: [2047 bits]
        checksum: 8d15
        keyid: C597AE9A8D35C3C9
# off=1819 ctb=b4 tag=13 hlen=2 plen=28
:user ID packet: "John Smith <jsmith@mock.org>"
# off=1849 ctb=89 tag=2 hlen=3 plen=566
:signature packet: algo 1, keyid C597AE9A8D35C3C9
        version 4, created 1631264750, md5len 0, sigclass 0x13
        digest algo 10, begin of digest c5 cb
        hashed subpkt 2 len 4 (sig created 2021-09-10)
        hashed subpkt 27 len 1 (key flags: 07)
        hashed subpkt 22 len 4 (pref-zip-algos: 2 3 1 0)
        hashed subpkt 11 len 3 (pref-sym-algos: 9 8 7)
        hashed subpkt 21 len 4 (pref-hash-algos: 10 9 8 11)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 25 len 1 (primary user ID)
        subpkt 16 len 8 (issuer key ID C597AE9A8D35C3C9)
        data: [4095 bits]
```
Note `sigclass 0x13`, I'd like to generate key with `sigclass 0x10`.

**Comment by vanitasvitae** [comment]
This is a tricky question.
You don't generate a "key with signature class XY", but you rather place a self-signature of type "XY" on it.

So the signature class really should not be exposed to the user when generating keys. Instead we probably want to allow the user to make customized signatures.
A sane signature builder API is something I'm working on at the moment.

In the mean time, the only way to get a 0x10 sig onto your key is by using BC directly.

**Comment by IvanPizhenko** [comment]
Thank you. Meanwhile I've found this SO: https://stackoverflow.com/questions/28245669

**Comment by vanitasvitae** [comment]
Btw: Could you create a list of what you'd expect a signature builder API to be capable of?
While the BC API is ugly due to the boiler plate code, I'm not totally convinced that I can come up with something more elegant.

If you could sketch out how you'd imagine using the API would be (eg. using pseudocode), that would help me :)

Edit: Not sure if you can see it, but I created https://github.com/pgpainless/pgpainless/projects/3 as a project (currently not much to see there)

**Comment by vanitasvitae** [comment]
(Since related to this discussion, [here](https://github.com/pgpainless/pgpainless/issues/177#issuecomment-917099633) I sketched out how to manually generate signatures with different signature class using BC and PGPainless at the moment)

**Comment by IvanPizhenko** [comment]
That's good question. I think I need to think of it. Generally... you just need to find a better way to present all what BC can do. Maybe provide some methods which provide some predefined settings for the often used scenarios. But can't provide any concrete ones at the moment. Maybe it is worth to ask the same question more people: @tomholub @DenBond7 @jerbell @rrrooommmaaa - what do you think? (for the question above https://github.com/pgpainless/pgpainless/issues/180#issuecomment-917115582)

**Comment by tomholub** [comment]
I tend to think the opposite - if users want to go to that depth to create very customized keys, then they might as well use BC directly. The strength of library like PGPainless is that it takes all of this complexity away and provides a simple API with sane defaults and, and some configurability that will be widely used (like ECC keys vs RSA when creating keys, which algorithms to accept when verifying and so on).

I'd say creating signatures of 0x-some vs 0x-other type should be out of scope for a convenience library of this type.

Not that it shouldn't be done if Paul thinks it worthwhile - that's up to him - I'm providing my point of view.

**Comment by vanitasvitae** [comment]
Yeah, we should probably re-set the focus of PGPainless to being just that: painless.
Maybe in the future it might make sense to move more powerful APIs into another module (pgpowerful? :P) which can then be used by pgpainless.

For now I will close this, as generating 0x10 sigs is out of scope.
