### ISSUE TITLE
NoClassDefFoundError: org/bouncycastle/util/Iterable

### ISSUE THREAD

**Issue by pmig** [pgpainless/pgpainless#181]
Hi,

Trace:

```
java.lang.ClassLoader in defineClass1
java.lang.ClassLoader in defineClass at line 1010
java.security.SecureClassLoader in defineClass at line 150
java.net.URLClassLoader in defineClass at line 512
java.net.URLClassLoader$1 in run at line 420
java.net.URLClassLoader$1 in run at line 414
java.security.AccessController in doPrivileged at line 691
java.net.URLClassLoader in findClass at line 413
java.lang.ClassLoader in loadClass at line 586
org.springframework.boot.loader.LaunchedURLClassLoader in loadClass at line 151
java.lang.ClassLoader in loadClass at line 519
org.pgpainless.key.parsing.KeyRingReader in readSecretKeyRing at line 160
org.pgpainless.key.parsing.KeyRingReader in secretKeyRing at line 69
```

I just included `pgpainless-core` in my parent maven file. Do I need to explicitly import some bouncycastle dependencies? 

In test scope everything works fine, das bouncycastle is inside my `.m2` folder.

**Comment by vanitasvitae** [comment]
Hey!

You probably also want to include `org.bouncycastle:bcprov-jdk15on:1.69`.

Let me know if that fixes your issue, so I can update the readme :)

Edit: PGPainless expects `org.bouncycastle:bcprov-jdk15on:1.69` to be available on your runtime classpath, so you definitely need to add it as a dependency in your project, eg.
```
    implementation `org.pgpainless:pgpainless-core:0.2.12`
    implementation `org.bouncycastle:bcprov-jdk15on:1.69`
```

**Comment by pmig** [comment]
Hi @vanitasvitae  - Yes indeed that was necessary. 

Do you think you could ship pgpainless with the correct bouncy castle version via a pom file?

**Comment by vanitasvitae** [comment]
The idea behind this decision was to allow some flexibility in dependency management, such that consumers could quickly replace bcprov with a newer version, should there be a security issue for example.

See https://github.com/pgpainless/pgpainless/discussions/184 and feel free to share your thoughts there :)
