### ISSUE TITLE
ECC curve25519/ed25519 compatibility

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#23]
I'm making a separate issue as this is particularly useful

- [x] key pair generation
- [x] message encryption
- [x] message decryption
- [x] message signing
- [x] message verification

Here are details from what openpgp.js supports. The most important to us is curve25519/ed25519 but if we can get the rest for free (eg by using a particular BC fork) that would be nice.

![image](https://user-images.githubusercontent.com/6306961/99794486-2421a800-2b22-11eb-9f75-dabbba3a9cc8.png)

**Comment by vanitasvitae** [comment]
I started working on this in https://github.com/pgpainless/pgpainless/tree/moreEllipticCurves :+1:

**Comment by vanitasvitae** [comment]
Migrated to #43
