### ISSUE TITLE
key generation parameters review

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#24]
@wiktor-k when you are done with current task on the KM, please review default parameters of generated keys using pgpainless. Things like the preferred hash algos, not supporting/encouraging SHA1 if possible, preferred symmetric encryption algos and so on. General structure of the key and compatibility with our software.

If there is anything to improve, please mention it here, else if all is good, you can then finish https://github.com/FlowCrypt/flowcrypt-key-manager/pull/490

**Comment by vanitasvitae** [comment]
Some reference: https://docs.sequoia-pgp.org/sequoia_openpgp/policy/struct.StandardPolicy.html
