### ISSUE TITLE
easier accessible information about keyring

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#25]
> detailed info about keys

Could you elaborate what exactly you mean by this? BC already has a lot of methods to get information about keys. What exactly is missing?

Maybe @wiktor-k could create a patch with an interface with methods that would be needed? Alternatively just create a new ticket with more information :)

_Originally posted by @vanitasvitae in https://github.com/pgpainless/pgpainless/issues/13#issuecomment-721317602_

-------------------

Here is an example from our own code (happens to be kotlin but should be very similar in Java). This is a list of information that we typically need about a key. I imagine pgpainless doesn't need exactly this interface, but whatever information we do query this way should be ideally easier to query, without all of this code. Particularly the code that cycles through packets should not be on the library user to write - figuring out expiration date, revocation date, last modified date, if the key is fully encrypted, etc.

You can skip the `emails` as that's a bit half baked.

It should be not too difficult to get a fingerprint out of the library in hex form like openpgp usually shares it (recommend uppercase hex string).

```kt

    @OptIn(ExperimentalUnsignedTypes::class)
    fun parse(keyRing: PGPKeyRing): Key {
        val key = keyRing.publicKey
        val id = bytesToHex(key.fingerprint)
        val ids = key.userIDs.iterator().asSequence().toList()
        val emailPattern = Pattern.compile("[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}")
        val emails = ids.asSequence().flatMap {
            // todo - better use JavaMail to parse this, as above, UTF emails won't work, and may have other quirks
            val matcher = emailPattern.matcher(it)
            if (matcher.find()) {
                listOf(matcher.group()).asSequence()
            } else {
                emptySequence()
            }
        }
        val lastModified = key.signatures.asSequence()
            .map { (it as PGPSignature) }
            .filter { it.keyID == key.keyID }
            .map { it.creationTime.time }
            .fold(0L, Math::max)
        val revokedDate = key.getSignaturesOfType(PGPSignature.KEY_REVOCATION).iterator().asSequence().map { (it as PGPSignature).creationTime }.firstOrNull()
        val isPrivate = when (keyRing) {
            is PGPSecretKeyRing -> true
            is PGPPublicKeyRing -> false
            else -> throw ParseError("Expected PGPKeyRing to be either PGPSecretKeyRing or PGPPublicKeyRing, got ${keyRing::class.java.name}")
        }
        val fullyDecrypted = if (keyRing is PGPSecretKeyRing) { // did the test again for Smart Cast
            // encrypt. algo. 0 means not encrypted https://tools.ietf.org/html/rfc4880#section-5.5.3
            keyRing.secretKeys.iterator().asSequence().all { it.keyEncryptionAlgorithm == 0 }
        } else {
            null // public key
        }
        if ((isPrivate && fullyDecrypted == null) || (!isPrivate && fullyDecrypted != null)) { // sanity check
            throw Exception("Unexpected combination: isPrivate=$isPrivate, fullyDecrypted=$fullyDecrypted")
        }
        return Key(
            type = KeypairType.openpgp,
            id = id,
            allIds = keyRing.publicKeys.iterator().asSequence().map { bytesToHex(it.fingerprint) }.toList().toTypedArray(),
            uids = ids.toList().toTypedArray(),
            expiration = if (key.validSeconds == 0L) null else Instant.ofEpochMilli(key.creationTime.time + key.validSeconds * 1000),
            created = Instant.ofEpochMilli(key.creationTime.time),
            lastModified = Instant.ofEpochMilli(lastModified),
            revocation = if (revokedDate != null) Instant.ofEpochMilli(revokedDate.time) else null,
            uidEmails = emails.toList().toTypedArray(),
            identities = ids.toTypedArray(),
            isPrivate = isPrivate,
            fullyDecrypted = fullyDecrypted
        )
    }
```

Thanks!

**Comment by tomholub** [comment]
So if I could for example do something like `key.getLastModified()` or `key.getExpiration(Usage.ENCRYPT)` or `key.getExpiration(Usage.SIGN)` etc - then our code I quoted above could me removed and instead we could use these methods.

**Comment by wiktor-k** [comment]
That's exactly what I had in mind, thanks for quoting the code @tomholub, I didn't get to that.

@vanitasvitae if you've got better ideas for naming or API design of course do bring it forward - the idea is to have easily accessible info without manually calling BC internals :)
