### ISSUE TITLE
ability to run compatibility tests with tests.sequoia-pgp.org?

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#26]
this is for later, recording here so it has separate issue

--------------------

> compatibility tests - core: we have accumulated some test cases from our own PGP apps (particularly in https://github.com/FlowCrypt/flowcrypt-browser ) that will be great to borrow the test vectors and test them also here in this library. It will probably uncover some blind spots.

This is important as basically there are two endpoints that need to talk to each other. FTR there is a broader project to test multiple OpenPGP implementations at https://tests.sequoia-pgp.org/ This utilizes [stateless OpenPGP CLI](https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-02) but this is probably out of scope for now :)

_Originally posted by @wiktor-k in https://github.com/pgpainless/pgpainless/issues/13#issuecomment-714471837_

**Comment by vanitasvitae** [comment]
That looks like a super-exciting project!
I agree that it is probably out of scope for now, but will definitely come in handy in the long run.

**Comment by vanitasvitae** [comment]
Progress is being tracked in https://github.com/pgpainless/pgpainless/tree/sop

Right now we can generate keys, export public keys, sign and verify documents, and add/remove armor.
Next up will be encryption and decryption and then we should be ready to plug into tests.sequoia-pgp.org
That will most certainly unveil bugs in PGPainless and give a good idea on what to tackle next.

**Comment by tomholub** [comment]
Excellent

**Comment by vanitasvitae** [comment]
There is a first (incomplete) prototype of a sop implementation available now in the pgpainless-sop module.

**Comment by vanitasvitae** [comment]
@teythoon just included PGPainless in the compatibility tests page: https://tests.sequoia-pgp.org/

**Comment by tomholub** [comment]
Nice! Is there a way to export areas to work on?

**Comment by vanitasvitae** [comment]
There are a [bunch of issues](https://github.com/pgpainless/pgpainless/issues?q=is%3Aissue+author%3Ateythoon) opened that got uncovered by the compat tests.
Looks like I have some work ahead of me :D
