### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#32]
One more thing. I think it'd be good to have GitHub Actions here and some basic Continuous Integration. I was quite surprised that this was all green here when I had the code locally fail :)

_Originally posted by @wiktor-k in https://github.com/pgpainless/pgpainless/pull/31#issuecomment-734902949_

**Comment by tomholub** [comment]
Agree, that's very useful. SemaphoreCI has 1300 minutes per month free and we've been quite happy with them. If it ever gets over, we'll sponsor the cost. Otherwise there's travis etc with free plans. This will be very helpful.

**Comment by vanitasvitae** [comment]
I already have [travis set up](https://travis-ci.org/pgpainless/pgpainless) for pgpainless, but it may not be configured ideally :D

**Comment by vanitasvitae** [comment]
I just verified that Travis is working when creating pull requests :) (see #34 )
