### ISSUE TITLE
withDefaultKeyFlags is very RSA centric

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#36]
The KeySpecBuilders `withDefaultKeyFlags` method adds the following keyflags to the key:
```
                KeyFlag.CERTIFY_OTHER,
                KeyFlag.SIGN_DATA,
                KeyFlag.ENCRYPT_COMMS,
                KeyFlag.ENCRYPT_STORAGE,
                KeyFlag.AUTHENTICATION
```
That's okay for RSA primary keys without additional subkeys, but is absolutely not suitable for most other configurations.

We should rework the process of generating key rings to make keyflags as transparent to the user while still generating sensible key rings.

**Comment by vanitasvitae** [comment]
A possible API could look somewhat like this:
```
PGPainless.generateKeyRing()
    .archetype()
        .rsaAndRsa()
...
        .dsaAndElgamal()
...
        .dsaSignOnly()
...
        .rsaOnlySignCertify()
...
        .dsa()
...
    .withCertificationKey() <- exactly once
        .withSignatureSubKey() <- 0:*
...
        .withEncryptionSubKey() <- 0:*
...
        .withCustomSubKey() <- 0:*

            .withUserId(userId)
            .{with|without}ExpirationDate()
            .
...
```

**Comment by tomholub** [comment]
Maybe @wiktor-k will have some comments later

**Comment by vanitasvitae** [comment]
I decided that for now its probably best to ditch the `withDefaultKeyFlags` method at all and let the user decide which flags to use on their keys (while preventing invalid choices of course).
