### ISSUE TITLE
Encryption- Decrytion API should integrate encryption with password

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#38]
Right now encryption/decryption with a passphrase is implemented independently from public key encryption.
Both methods should be supported (even in parallel) using the same API, so that it is possible to encrypt a message to a public key and a passphrase at the same time.

**Comment by vanitasvitae** [comment]
This has been addressed in the SOP branch.
It is now possible to provide recipient public keys AND passphrases in parallel during encryption.
The resulting ciphertext will be decryptable by providing either a recipient secret key or a passphrase.

Similarly it is now possible to either provide a recipient secret key OR a passphrase during decryption.

What might be worth looking into is some mechanism that allows to inspect ciphertext to detect recipient keys and/or passphrases. Currently the API expects the user to know how the ciphertext was produced and expects them to provide decryption keys / passphrases on their own. A more advanced API might allow the user to discover which keys were used to encrypt the data and if it is possible to use a passphrase for decryption.

**Comment by tomholub** [comment]
> What might be worth looking into is some mechanism that allows to inspect ciphertext to detect recipient keys and/or passphrases. Currently the API expects the user to know how the ciphertext was produced and expects them to provide decryption keys / passphrases on their own. A more advanced API might allow the user to discover which keys were used to encrypt the data and if it is possible to use a passphrase for decryption.

Definitely, this is particularly useful in two cases:
 - when there is a key mismatch error - I'd like to know which key is the thing encrypted for
 - when the keys I'm using are encrypted with a pass phrase themselves. Decrypting a private key is an expensive operation - in fact I may need to ask the user for the pass phrase before decrypting the key. The user may have several keys. I need to know which key to ask the user to give me pass phrase for, and then I can actually decrypt the message.

An interesting quirk here is that while normally the key id is properly included, sometimes the sending client may have instead included a wildcard `\x0000000000000000` meaning that they don't want to disclose the key id for privacy reasons. The pgpainless should understand this situation, which means to attempt with all provided keys (in case you filter provided keys based on this information before trying to decrypt. if you don't, then it probably doesn't matter).

**Comment by vanitasvitae** [comment]
> The user may have several keys. I need to know which key to ask the user to give me pass phrase for, and then I can actually decrypt the message.

Thats a very good example of a usecase, so I will definitely look into this.

Hidden recipients will be an interesting challenge as well and definitely belong onto the roadmap.

**Comment by vanitasvitae** [comment]
Encrypting / Decrypting messages with a passphrase is now part of the main encryption API.
I opened #42 for the case of hidden recipients.
