### ISSUE TITLE
Add sessionKey to OpenPgpMetadata

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#40]
This will allow the user to learn about the session key that was used to encrypt a message.
This task consists of these subtasks:
* [ ] Extracting the session key when decrypting a message
  * [ ] Making the extracted key available to the user by adding `getSessionKey()` to the `OpenPgpMetadata` class
* [ ] Using a custom session key when encrypting a message

**Comment by vanitasvitae** [comment]
It is not clear to me how we could extract the sessionkey during decryption. Maybe another patch to BC is required?

**Comment by tomholub** [comment]
Is there no API in BC to do this before decryption? Or does it have to be exactly "during"? (probably misunderstood the issue)

**Comment by vanitasvitae** [comment]
By "during decryption" I mean that there is no way to learn the session key at all.
The session key decryption is abstracted away in BC, so we cannot access the session key as far as I can see.

**Comment by tomholub** [comment]
I see - got it.

**Comment by vanitasvitae** [comment]
I just created https://github.com/bcgit/bc-java/pull/1030 upstream, to finally tackle this issue :)

**Comment by vanitasvitae** [comment]
The upstream PR also contains a handy `PGPSessionKey` class consisting of algorithm id and session key.
It further handles (de-)serializing GnuPG ASCII session keys.

**Comment by vanitasvitae** [comment]
Upstream implemented a slightly modified version of my proposal: https://github.com/bcgit/bc-java/commit/28874e81b6e92c923f93900ddea9a726451f946e

**Comment by vanitasvitae** [comment]
Done.
