### ISSUE TITLE
Support for decryption of messages with hidden recipient

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#42]
As @tomholub [noted](https://github.com/pgpainless/pgpainless/issues/38#issuecomment-751391779):
> Definitely, this is particularly useful in two cases:
> *   when there is a key mismatch error - I'd like to know which key is the thing encrypted for
> *   when the keys I'm using are encrypted with a pass phrase themselves. Decrypting a private key is an expensive operation - in fact I may need to ask the user for the pass phrase before decrypting the key. The user may have several keys. I need to know which key to ask the user to give me pass phrase for, and then I can actually decrypt the message.
>
> An interesting quirk here is that while normally the key id is properly included, sometimes the sending client may have instead included a wildcard \x0000000000000000 meaning that they don't want to disclose the key id for privacy reasons. The pgpainless should understand this situation, which means to attempt with all provided keys (in case you filter provided keys based on this information before trying to decrypt. if you don't, then it probably doesn't matter).

Decrypting messages for hidden recipients will probably fail at the moment. We should add support for that.

**Comment by vanitasvitae** [comment]
Messages that were encrypted using hidden recipients can now be successfully decrypted :partying_face: 

Next we should add a way to make the user aware of hidden recipient keys maybe?

**Comment by tomholub** [comment]
> Next we should add a way to make the user aware of hidden recipient keys maybe?

As long as I can pull out a list of longids, if one of them is 0x000... that's enough. I don't think we need anything more for that, it's an edge scenario.
