### ISSUE TITLE
UserId order of params

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#45]
This may not be the best ordering:

```java
    public UserId(String name, String comment, String email) {
        this.name = name;
        this.comment = comment;
        this.email = email;
    }
```

Because the most likely input for me to want to enter is email, second is name, and comment is the least likely - I think it would ideally be ordered in that order.

Even better if there were overloads so that I could enter only email or only email + name.

**Comment by vanitasvitae** [comment]
I will look into it.

**Comment by tomholub** [comment]
But I understand that's it's a nasty incompatibility to introduce - if someone wrote UserId("Joe", "", "joe@corp.co") then this would reshuffle their working code. On the other hand, it is in alpha stage.. I'll leave it up to you.

**Comment by vanitasvitae** [comment]
I may make the Constructor of UserID private in favor of factory methods (`UserID.fromEmail(String)`, `UserID.fromName(String)`, etc.).
That should solve the disambiguity.

**Comment by tomholub** [comment]
Interesting. I didn't think that userid could have a name but no email. Theoretically it could. Maybe I'm warped by our specific usecase - I see emails everywhere.

**Comment by vanitasvitae** [comment]
Yeah, the UserID is pretty much a freeform text field which can contain arbitrary data but for emails they follow a convention.
