### ISSUE TITLE
mention which curve simpleEcKeyRing is using + consider changing to Curve25519

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#46]
```
    /**
     * Creates a key ring consisting of an ECDSA master key and an ECDH sub-key.
     * The ECDSA master key is used for signing messages and certifying the sub key.
     * The ECDH sub-key is used for encryption of messages.
     *
     * @param userId user-id
     * @param password Password of the private key. Can be null for an unencrypted key.
     *
     * @return {@link PGPSecretKeyRing} containing the key pairs.
     *
     * @throws PGPException
     * @throws NoSuchAlgorithmException
     * @throws InvalidAlgorithmParameterException
     */
    public PGPKeyRing simpleEcKeyRing(@Nonnull String userId, String password)
```

I think the comment should mention this. I digged in the code and it seems that P256 is the chosen curve. 

Separately, would it be ok to settle on Curve25519 as the default one?

**Comment by vanitasvitae** [comment]
Yeah this should be fixed and I guess curve25519 would be indeed a good candidate for the default curve.

**Comment by tomholub** [comment]
Excellent - thanks!

**Comment by tomholub** [comment]
However there seems to be just one curve - does this still need to be implemented?

```java
public enum EllipticCurve {
    _P256("P-256"),
    ;

    private final String name;

    EllipticCurve(@Nonnull String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}

```

**Comment by tomholub** [comment]
I do see master has more but not yet curve25519

```java

public enum EllipticCurve {
    _P256("P-256"),
    _P384("P-384"),
    _P521("P-521"),
    ;

    private final String name;

    EllipticCurve(@Nonnull String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
```

**Comment by vanitasvitae** [comment]
I might be wrong, but I read that curve25519 for signing is known as ed25519 (which is found [here](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/main/java/org/pgpainless/key/generation/type/eddsa/EdDSACurve.java) on current master) and for encryption as XDH (which is found [here](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/main/java/org/pgpainless/key/generation/type/xdh/XDHCurve.java)).

I planned ti interview viktor about this soon :D

**Comment by tomholub** [comment]
Let's ping @wiktor-k in case he has thoughts

**Comment by tomholub** [comment]
What would the keygen parameters then look like? Is it something like this?

I'm also not too familiar with this terminology, just trying to get an idea of what it will look like.

```
// encryption
KeyType.EDDSA(EllipticCurve._25519)

// signing
KeyType.XDH(EllipticCurve._25519)
```

**Comment by vanitasvitae** [comment]
It would be like
```
// signing
KeyType.EDDSA(EdDSACurve.ED25519)
// encryption
KeyType.XDH(XDHCurve.X25519)
```
A real example can be found [here](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/test/java/org/pgpainless/key/generation/GenerateEllipticCurveKeyTest.java#L36)

**Comment by tomholub** [comment]
I see. That means that curve25519 support seems to just be awaiting a release. Then once we are sure that this is the right setup, we could switch it to the default.

Is the master ready for a release that includes this functionality? A relase with this to experiment with would be very helpful :)

**Comment by vanitasvitae** [comment]
The master should be more or less ready to go. I will try to create a release until the end of the week, however I can give no guarantee as I'm currently busy with sad family events :/

**Comment by tomholub** [comment]
I'm very sorry to hear that - I send my best wishes your way.

No worries, code can wait. Family first

**Comment by wiktor-k** [comment]
Looks good @tomholub and @vanitasvitae :+1: 

I see on the horizon that curve 448 (goldilocks, Ed448) is being considered for inclusion in OpenPGP and on first sight it seems it would fit your design well Paul so that's nice :)

**Comment by vanitasvitae** [comment]
I just published version 0.2.0-alpha5 :)

**Comment by tomholub** [comment]
Excellent, thank you!

**Comment by vanitasvitae** [comment]
I switched the `simpleEcKeyRing()` methods over to use curve25519 instead of p256.
Additionally there is now `modernKeyRing()` which generates a key ring consisting of an ed25519 EdDSA primary key used only to certify another ed25519 EdDSA signing subkey and an X25519 XDH encryption subkey.

I'm not yet 100% satisfied with the name, so if you have any suggestions, let me know :)
