### ISSUE TITLE
key genrator order and usage questions

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#47]
I see that you usually define keys in this order:

```kt
                .withSubKey(KeySpec.getBuilder(KeyType.XDH(XDHCurve._X25519))
                        .withKeyFlags(KeyFlag.ENCRYPT_COMMS)
                        .withDefaultAlgorithms())
                .withMasterKey(KeySpec.getBuilder(KeyType.EDDSA(EdDSACurve._Ed25519))
                        .withKeyFlags(KeyFlag.CERTIFY_OTHER, KeyFlag.SIGN_DATA)
                        .withDefaultAlgorithms())
```

Subkey first, master key after. It doesn't really matter which order the user puts it, right? So it's equivalent to:

```kt
                .withMasterKey(KeySpec.getBuilder(KeyType.EDDSA(EdDSACurve._Ed25519))
                        .withKeyFlags(KeyFlag.CERTIFY_OTHER, KeyFlag.SIGN_DATA)
                        .withDefaultAlgorithms())
                .withSubKey(KeySpec.getBuilder(KeyType.XDH(XDHCurve._X25519))
                        .withKeyFlags(KeyFlag.ENCRYPT_COMMS)
                        .withDefaultAlgorithms())
```

I'm asking because it confused me more than once. When you print out key contents (serialized/armored key) you'll find master key first, then subkeys following the master key. If either works for the generator, I'd consider switching the convention in code samples and maybe code too.

Another question is regarding the generator, consider this code:

```kt
        var generate = PGPainless.generateKeyRing()
            .withSubKey(
                KeySpec.getBuilder(encryptionKeyType)
                    .withKeyFlags(KeyFlag.ENCRYPT_COMMS, KeyFlag.ENCRYPT_STORAGE)
                    .withDefaultAlgorithms()
            )
            .withMasterKey(
                KeySpec.getBuilder(signingKeyType)
                    .withKeyFlags(KeyFlag.SIGN_DATA, KeyFlag.CERTIFY_OTHER)
                    .withDefaultAlgorithms()
            )
            .withPrimaryUserId(users.first())
        for(user in users.drop(1)) {
            generate = generate.withAdditionalUserId(user)
        }
        val keyRing = generate.withoutPassphrase().build()
```

Is it necessary to do ` generate = generate.withAdditionalUserId(user)` or is `generate.withAdditionalUserId(user)` enough? This is one thing that always confused me with Java (or other generators), whether the convention and expectation is that the last value is the one that matters or whether it edits the existing object, making whatever it returns the same thing as the original.

**Comment by vanitasvitae** [comment]
> It doesn't really matter which order the user puts it, right? So it's equivalent to...

You have to specify the subkeys first and then the masterkey because each step returns another builder object with different methods.

I have designed it that way so that the user can call the `withMasterKey` method only once, but `withSubKey` multiple times.
The `withMasterKey` method can be seen as "okay, this is enough sub keys, now the master key" :D
In your example it is okay to simply call `generate.withAdditionalUserId(user)` and omit the assignment, as this particular builder step returns `this`.
This is however not always the case.

**Comment by tomholub** [comment]
I see, so it is by design. It's a minor thing - but good to know. I'll close this, thanks!
