### ISSUE TITLE
interop with gnupg

### ISSUE THREAD

**Issue by hoebat** [pgpainless/pgpainless#5]
how well does the library work with gnupg? i.e, is it possible to have good interop with gnupg with:
- import and export keys
- encrypt/decrypt
- sign/verify

**Comment by vanitasvitae** [comment]
All this should work, although I haven't tested it super extensively yet.
Importing RSA/EC keys should work though.
Encrypting and decrypting should work as well, still there might be some more exotic algorithms that are not supported.
Same for signing.

Edit: This lib is a wrapper around Bouncycastles OpenPGP API, so it should be capable of everything that Bouncycastle is capable of.

**Comment by hoebat** [comment]
Thanks. I'll give this a go. the BC libraries are seriously a pain to use. Very happy to have found this lib.

**Comment by vanitasvitae** [comment]
Great! Keep in mind, that this library is still in an early state of development. Let me know if something doesn't work as expected :)
