### ISSUE TITLE
Set key expiration time during key creation

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#50]
Currently it is possible to change a keys expiration date by calling
```java
secretKeys = PGPainless.modifyKeyRing(secretKeys)
    .setExpirationDate(date, secretKeysProtector)
    .done();
```
or for a specific subkey
```java
secretKeys = PGPainless.modifyKeyRing(secretKeys)
    .setExpirationDate(subkeyFingerprint, date, secretKeysProtector)
    .done();
```

It would be nice to specify an expiration date during the key creation process, eg.
```
PGPSecretKeyRing keyRing = PGPainless.generateKeyRing()
                .withSubKey(KeySpec.getBuilder(KeyType.XDH(XDHCurve._X25519))
                        .withKeyFlags(KeyFlag.ENCRYPT_COMMS)
                        .withDefaultAlgorithms())
                .withMasterKey(KeySpec.getBuilder(KeyType.EDDSA(EdDSACurve._Ed25519))
                        .withKeyFlags(KeyFlag.CERTIFY_OTHER, KeyFlag.SIGN_DATA)
                        .withDefaultAlgorithms()
                        .withExpirationDate(date)) // <- like this for example
                .withPrimaryUserId(UserId.onlyEmail("alice@wonderland.lit").toString())
                .withoutPassphrase()
                .build();
```

Maybe we can rework the generation API once again to be able to set arbitrary subpackets on the key without adding too much complexity to the API.

Was #48

**Comment by tomholub** [comment]
> though I don't think this is of high priority right now.

This depends on whether the key/signature structure of the create -> update procedure is different from creating expiring key in a single step.

Are there going to be some additional / old signatures present? Any other difference in structure?

If they end up having the exact same structure, then we'll be ok as it is now - with the idea that ability to create expiring keys directly will be added sometime in the future.

The advantage of having this directly in the keygen API is that we can make some decisions on behalf of the library user. Eg should I be expiring the primary key, the subkey, or both? This shouldn't be something that the library user would have to think about, instead we should do whatever is the most common behavior (or whatever OpenPGP.js does).

**Comment by vanitasvitae** [comment]
> Are there going to be some additional / old signatures present? Any other difference in structure?

Changing the expiry date will add a new signature to the key, which will contain all the subpackets of the old key, but an altered expiration date. The signature will have the same structure as the old one.

> Eg should I be expiring the primary key, the subkey, or both?

The API currently allows for both cases.
Expiring both primary and subkey would look like this:
```java
expiry = new Date();
secretKeys = PGPainless.modifyKeyRing(secretKeys)
    .setExpirationDate(expiry, secretKeysProtector)
    .setExpirationDate(subkeyFingerprint, expiry, secretKeysProtector)
    .done();
```

**Comment by vanitasvitae** [comment]
Would you say that it might be a good idea to have
```java
secretKeys = PGPainless.modifyKeyRing(secretKeys)
    .setExpirationDateOfAllKeys(expiry, secretKeysProtector)
    .done();
```
to expire the whole key ring (all subkeys)?

**Comment by tomholub** [comment]
> Changing the expiry date will add a new signature to the key, which will contain all the subpackets of the old key, but an altered expiration date. The signature will have the same structure as the old one.

Does this mean that it results in two signatures on the key? One original, and one expiring? Or is the original signature removed / replaced?

**Comment by tomholub** [comment]
> Would you say that it might be a good idea to have
> 
> ```java
> secretKeys = PGPainless.modifyKeyRing(secretKeys)
>     .setExpirationDateOfAllKeys(expiry, secretKeysProtector)
>     .done();
> ```
> 
> to expire the whole key ring (all subkeys)?

I'm not entirely sure what the convention is - exactly what is the most common method of expiring / extending pgp keys. I imagine some people to only expire the encryption subkeys, and then maybe renew signatures for those. I imagine others may be doing it on the whole key. It would be good to know what the consensus / recommended method is. Maybe @wiktor-k will have some thoughts

**Comment by vanitasvitae** [comment]
> Does this mean that it results in two signatures on the key? One original, and one expiring? Or is the original signature removed / replaced?

I asked the sequioa-pgp devs and they recommended adding a signature instead of replacing the old one.
I *think* that GnuPG replaces the signature instead.

**Comment by vanitasvitae** [comment]
> I'm not entirely sure what the convention is - exactly what is the most common method of expiring / extending pgp keys.

Me neither. Apparently the sequoia community is working on a document that describes how to "use" the openpgp specifications building blocks to model certain use cases, but they haven't yet gotten so far.

Having such a document would be very valuable addition to the ecosystem.

**Comment by tomholub** [comment]
> I asked the sequioa-pgp devs and they recommended adding a signature instead of replacing the old one.

Meaning - the pgp key indeed ends up having contents that are a bit different compared to if the first-ever signature was already expiring. (do not know any better then sequoia-pgp regarding what is the right approach, so I'll take their word for it)

As a result, it's not possible for create + update to be fully equivalent to creating already expiring key - with that in mind, I think the ability to create already expiring key gains some more importance

**Comment by tomholub** [comment]
> > I'm not entirely sure what the convention is - exactly what is the most common method of expiring / extending pgp keys.
> 
> Me neither. Apparently the sequoia community is working on a document that describes how to "use" the openpgp specifications building blocks to model certain use cases, but they haven't yet gotten so far.
> 
> Having such a document would be very valuable addition to the ecosystem.

Could you point me to where these discussions were taking place? This would indeed be valuable.

**Comment by vanitasvitae** [comment]
The existing documentation can be found [here](https://hkos.gitlab.io/openpgp-notes/keys.html).
The discussion is taking place in #sequoia on freenode irc.

**Comment by vanitasvitae** [comment]
This is now possible:
```
        PGPSecretKeyRing secretKeys = PGPainless.generateKeyRing()
                .withPrimaryKey(KeySpec.getBuilder(KeyType.RSA(RsaLength._3072))
                        .withKeyFlags(KeyFlag.CERTIFY_OTHER, KeyFlag.SIGN_DATA, KeyFlag.ENCRYPT_COMMS)
                        .withDefaultAlgorithms())
                .withPrimaryUserId("primary@user.id")
                .setExpirationDate(expiration)
                .withoutPassphrase()
                .build();
```

I'm thinking of setting a default expiration date in the simplified key generation methods (eg. `simpleEcKeyRIng()` etc.).
What do you think of an expiration date of 3 years?

**Comment by tomholub** [comment]
Thanks!

I would not do an implicit expiration. I think that could really surprise
folks. There could be a method signature that accepts expiration though.

**Comment by tomholub** [comment]
> This is now possible:
> 
> ```
>         PGPSecretKeyRing secretKeys = PGPainless.generateKeyRing()
>                 .withPrimaryKey(KeySpec.getBuilder(KeyType.RSA(RsaLength._3072))
>                         .withKeyFlags(KeyFlag.CERTIFY_OTHER, KeyFlag.SIGN_DATA, KeyFlag.ENCRYPT_COMMS)
>                         .withDefaultAlgorithms())
>                 .withPrimaryUserId("primary@user.id")
>                 .setExpirationDate(expiration)
>                 .withoutPassphrase()
>                 .build();
> ```
> 

It looks good as it is now - if this has been released, I suppose this issue can be closed? Thanks!
