### ISSUE TITLE
Check validity of userIDs

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#59]
UserIDs can be revoked. We should let the user get insight into which userIDs are currently valid and which are expired/revoked.

**Comment by vanitasvitae** [comment]
```java
KeyRingInfo info = PGPainless.inspectKeyRing(secretKeys);
List<String> validUserIDs = info.getValidUserIds();
boolean isValid = info.isValidUserId("Juliet Capulet <juliet@capulet.lit>");
```

**Comment by tomholub** [comment]
It will be definitely helpful to document these new APIs - making the various things that the library can do more discoverable.

**Comment by vanitasvitae** [comment]
As always those functions do have Javadoc attached, although we could add a hint to the older `getUserIDs()` method, noting that that method also returns revoked and expired userIDs and that the new method should be used instead.
