### ISSUE TITLE
testing primary uids on created keys

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#62]
How could this issue be tested? Since it was fixed without adding any test, it may get broken in the future.

> I agree, I didn't find a way in PGPainless to check for primary user ID value. It gives all the users list for which test was already added.

Normally I assume the first returned uid is the primary one. Is that guaranteed in pgpainless? Or is actually the way to choose primary uid a different mechanism?

_Originally posted by @tomholub in https://github.com/pgpainless/pgpainless/issues/60#issuecomment-769621392_

Just re-posting here so it doesn't get lost

**Comment by vanitasvitae** [comment]
PGPainless currently returns the first userID in the userID list, so it does not check for the userId subpacket.
We should change that.

**Comment by vanitasvitae** [comment]
Now there is `keyRingInfo.getPrimaryUserId()` which will only return the userID that is marked as primary by a signature.
