### ISSUE TITLE
Possible new module: pgpainless-autocrypt

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#71]
It might be a nice idea to create a new module which implements [Autocrypt](https://autocrypt.org/level1.html).
The module would be opinionated and simplify operations like creating keys etc. by following the autocrypt recommendations

What do you think?

**Comment by tomholub** [comment]
Not an immediate need on our end, but would be nice eventually.

I'm not sure that Autocrypt handles creating keys? The only thing I can foresee using (on Android) is creating autocrypt email header, and parsing autocrypt email header, for public key exchange and knowing rules for automatic encryption.

**Comment by vanitasvitae** [comment]
fyi, there is https://github.com/iNPUTmice/lttrs-autocrypt

**Comment by vanitasvitae** [comment]
Out of scope for now.
