### ISSUE TITLE
Introduce Options classes for customization settings

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#73]
Right now we already have quite long builders for some operations.
Most already contain some options that we can hide behind an options class, eg
```
        EncryptionStream encryptionStream = PGPainless.encryptAndOrSign(
                      EncryptionStream.Purpose.STORAGE <--
                 )
                .onOutputStream(out)
                .toRecipients(keys)
                .andToSelf(KeyRingUtils.publicKeyRingFrom(cryptieKeys))
                .usingAlgorithms(SymmetricKeyAlgorithm.AES_192, HashAlgorithm.SHA384, CompressionAlgorithm.ZIP) <--
                .signWith(SecretKeyRingProtector.unlockSingleKeyWith(TestKeys.CRYPTIE_PASSPHRASE, cryptieSigningKey), cryptieSigningKey)
                .signCanonicalText() <--
                .asciiArmor(); <--
```

Ideally the easiest method call would not mention these options and just use a default options object that comes with sensible defaults.
However, the user must be able to modify these options, eg.
```
EncryptionStream encryptionStream = PGPainless.encryptAndOrSign(options)
                .onOutputStream(out)
                .toRecipients(keys)
                ...
```

I think by using an options object instead of chained builder steps we can further simplify the API and the code in the future.

I see that this is not an urgent issue at all, but maybe we can aim to redesign some APIs for a 0.3/0.4 release?

**Comment by tomholub** [comment]
I'm not a big fan of builders, so this would be welcome - as you say, not urgent

**Comment by vanitasvitae** [comment]
This was implemented in version 0.2.0-alpha12, which I just released.

**Comment by vanitasvitae** [comment]
@tomholub feel free to extensively explore the new version of PGPainless. I'm planning to release version 0.2 (no alpha!) soon, so let me know if there are things you'd like to see changed/added/fixed for that release :)

**Comment by tomholub** [comment]
I'm currently not able to have a look. Maybe if you release a 0.2-alpha first, then someone on our team could try to upgrade to it and that way highlight any friction points? Once we confirm, then you'd do 0.2 non-alpha?

**Comment by vanitasvitae** [comment]
sure, alpha12 has been released :)

**Comment by tomholub** [comment]
All good on our end - the new API is good.
