### ISSUE TITLE
PGPainless should not emit an uncompressed compressed data packet

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#74]
Even though that is a MUST implement, some implementations don't, and this creates interoperability problems.

See:
  - https://tests.sequoia-pgp.org/#Encrypt-Decrypt_roundtrip_with_key__Bob_
  - https://tests.sequoia-pgp.org/#Compression_Algorithm_support

**Comment by vanitasvitae** [comment]
This is about the "encryption phase" right?
So if the recipients key does not support any compression, PGPainless should not wrap the LiteralDataPacket in a CompressedDataPacket with algorithms NULL, but instead directly place the LiteralDataPacket in the EncryptedDataPacket, right?

**Comment by teythoon** [comment]
Yes.
