### ISSUE TITLE
PGPainless should support wildcard recipient ids

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#76]
See https://tests.sequoia-pgp.org/#Recipient_IDs

**Comment by vanitasvitae** [comment]
Huh, I thought I had already implemented this (see https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/test/java/org/pgpainless/decryption_verification/DecryptHiddenRecipientMessage.java). Glad to revisit this, as it appears that the implementation is not yet correct :)
