### ISSUE TITLE
PGPainless should treat signatures using insecure hash algorithms as invalid

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#81]
The situation is a bit more nuanced when it comes to certifications, but for signatures over data, MD5, SHA1, and RipeMD160 should be rejected.

See:
  - https://tests.sequoia-pgp.org/#Detached_Sign-Verify_roundtrip_with_key__Bob___MD5
  - https://tests.sequoia-pgp.org/#Detached_Sign-Verify_roundtrip_with_key__Bob___SHA1
  - https://tests.sequoia-pgp.org/#Detached_Sign-Verify_roundtrip_with_key__Bob___RipeMD
  - https://tests.sequoia-pgp.org/#Signature_over_the_shattered_collision
  - https://docs.sequoia-pgp.org/sequoia_openpgp/policy/enum.HashAlgoSecurity.html

Edit: Fixed link.

**Comment by vanitasvitae** [comment]
What is the point of the [these](https://tests.sequoia-pgp.org/#Signature_over_the_shattered_collision) tests?
Should an implementation blacklist those hash sums explicitly or is it enough to simply reject SHA-1 signatures?

**Comment by teythoon** [comment]
The motivation for this test is two-fold.  First, it is an impressive demonstration of a practical attack.  Second, there are actually two ways to defend against it:

First and foremost, the signature should be rejected because it was made by a broken algorithm.  Second, you can try to detect the attack.  For example, Sequoia also uses [SHA1CD](https://github.com/cr-marcstevens/sha1collisiondetection) instead of SHA1, and this also detects the attack.

**Comment by vanitasvitae** [comment]
I see.
I guess detection of the attack is out of scope for now, but rejection of SHA-1 definitely will make it to the roadmap :+1:
