### ISSUE TITLE
PGPainless emits a 'Version' header in the ASCII armor

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#82]
While there are other methods of implementation fingerprinting, we pretty much agree that advertising the version of the software used to create artifacts is not a good idea.

**Comment by vanitasvitae** [comment]
Alright, I'll look into how to change the header when using BC.

Edit: Maybe we can even upstream a fix.

**Comment by vanitasvitae** [comment]
I opened https://github.com/bcgit/bc-java/pull/889 upstream.
