### ISSUE TITLE
Marker packets must be ignored

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#84]
See:
  - https://tests.sequoia-pgp.org/#Marker_Packet
  - https://tests.sequoia-pgp.org/#Perturbed_certificates

**Comment by vanitasvitae** [comment]
I created https://github.com/bcgit/bc-java/pull/891 to fix the marker packet issue upstream.

**Comment by vanitasvitae** [comment]
I'll close this once BC is bumped to a fixing version.
