### ISSUE TITLE
Improve class UserId

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#91]
Here's what we'd like to see there:

- method equals()
- method hashCode()
- getters for name, email, comment
- proper formatting if name and comment are empty or null
- better builder

**Comment by IvanPizhenko** [comment]
will post a PR

**Comment by vanitasvitae** [comment]
0.2.0-alpha8 has been released :)

**Comment by IvanPizhenko** [comment]
Thank you!
