### ISSUE TITLE
Little issues with the SOP frontend

### ISSUE THREAD

**Issue by teythoon** [pgpainless/pgpainless#93]
First, the version string has not the expected form.  It should have two fields, separated by a space.

```
$ /home/teythoon/repos/pep/pgpzoo/bin/pgpainless-sop version
PGPainless CLI version 0.0.1
```

Second, the command line parser does not correctly communicate parsing failures (note that there are specific status codes for communicating errors in the spec):

```
$ /home/teythoon/repos/pep/pgpzoo/bin/pgpainless-sop foo ; echo status is $?
Unmatched argument at index 0: 'foo'
Usage: <main class> [COMMAND]
Commands:
  armor         Add ASCII Armor to standard input
  dearmor       Remove ASCII Armor from standard input
  decrypt       Decrypt a message from standard input
  encrypt       Encrypt a message from standard input
  extract-cert  Extract a public key certificate from a secret key from
                  standard input
  generate-key  Generate a secret key
  sign          Create a detached signature on the data from standard input
  verify        Verify a detached signature over the data from standard input
  version       Display version information about the tool
status is 0
```

Third, I noted that `generate-key` only accepts a single user id.

**Comment by vanitasvitae** [comment]
Good finding! I'll fix those for the next release (also I will sync the version of the SOP module with the core modules version).

**Comment by vanitasvitae** [comment]
Format of the version command output has been fixed in https://github.com/pgpainless/pgpainless/commit/8e3b61b76e377372289a48b45563b67df89a2ec4
