### ISSUE TITLE
Survey: API usage toRecipients

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#98]
Proper signature validation on keys will require some changes to the API.
I'm therefore considering to drop some methods from the encryption API that work with PGPPublicKeyRingCollections.

Which methods of the encryption API do you use? Do you primarily use...

* `toRecipients(PGPPublicKey... keys)` (will get dropped)
* `toRecipients(PGPPublicKeyRing... keyRings)` (will be kept/augmented)
* `toRecipients(PublicKeySelectionStrategy selectionStrategy<O>, MultiMap<O, PGPPublicKeyRingCollection> keys)` (very likely to be dropped/changed)

Same for verification of signatures (verifyWith). How does your typical API call with PGPainless look like?

**Comment by vanitasvitae** [comment]
As a heads-up: The API will also evolve in the sense that it will select suitable algorithms for encryption/signing based on which keys are involved.

**Comment by tomholub** [comment]
Here's one example on our end:

```kt
object PgpEncrypt {
  @Throws(IOException::class)
  fun encryptFile(srcInputStream: InputStream, destOutputStream: OutputStream, pgpPublicKeyRingCollection: PGPPublicKeyRingCollection) {
    srcInputStream.use { srcStream ->
      destOutputStream.use { outStream ->
        val builder = PGPainless.encryptAndOrSign()
            .onOutputStream(outStream)
            .toRecipients(pgpPublicKeyRingCollection)
            .usingSecureAlgorithms()

        builder.doNotSign().noArmor().use { encryptionStream ->
          srcStream.copyTo(encryptionStream)
        }
      }
    }
  }
```

**Comment by vanitasvitae** [comment]
Thanks for the feedback.
Does the PGPPublicKeyRingCollection contain keys of the same contact or any recipients?

**Comment by tomholub** [comment]
I believe it could contain public keys of various people - at a minimum your own plus the one of the recipient.

**Comment by vanitasvitae** [comment]
Further thinking about this:

If the user wants to encrypt a message for a single recipient, the key is provided in `toRecipient(publicKeyRing)`.
PGPainless then has to parse the key, checking whether or not it is still valid at this point (non-revoked, non-expired). Furthermore it has to inspect self-signatures to retrieve the keys algorithm preferences and to select the eligible encryption subkey(s).

(at the moment the user has to select algorithms by themselves, which is unfortunate)

If the user wants to encrypt to more than just one recipient, PGPainless has to gather the algorithm preferences of all those keys and select a common denominator. Additionally, PGPainless will come with a Policy class that sets minimum standards (like, do not use SHA1 for signing, use at least AES128...).

How would you design the API around these requirements?
I was thinking about deprecating `toRecipients(PGPPublicKeyRingCollection)`, as it does not grant fine controll over the keys.
Imagine there is a revoked/invalid key in the collection; should PGPainless throw an exception in that case or should it quietly drop that key from the encryption process?

Chaining multiple `toRecipient(PGPPublicKeyRing).and()` calls together for each intended recipient publicKeyRing would give finer grained control. Now PGPainless could throw an exception if an invalid key is encountered. Invalid in this case could mean that the key has been revoked or expired or that there is no eligible encryption subkey. Maybe we could even throw if there is no encryption subkey that supports our minimum algorithm preferences.

As mentioned above, PGPainless has to select a common denominator from all recipient keys algorithm preferences.
There might be a situation where there is no common denominator (eg. key1 prefers `[AES128]`, while key2 wants `[AES256]` only. In such case PGPainless would fall back to a default algorithm (likely AES256).
In such a situation, should the implementation still encrypt the message (with AES256) for the key which wants AES128? Probably, right?

I just noticed that this comment is mostly muttering around, but I'm racking my brain about this for some time now and would like to incorporate you into my decision process.

**Comment by vanitasvitae** [comment]
Also: If there are more than one eligible encryption subkey on a keyring, should we encrypt for each of them or select "the best" one only?

**Comment by tomholub** [comment]
>  Imagine there is a revoked/invalid key in the collection; should PGPainless throw an exception in that case or should it quietly drop that key from the encryption process?

Definitely throw an exception. Leaving things out silently is a bad practice because it produces behavior that's hard to notice, causing bugs that are hard to track.

> Chaining multiple toRecipient(PGPPublicKeyRing).and() calls together for each intended recipient publicKeyRing would give finer grained control. Now PGPainless could throw an exception if an invalid key is encountered. Invalid in this case could mean that the key has been revoked or expired or that there is no eligible encryption subkey. Maybe we could even throw if there is no encryption subkey that supports our minimum algorithm preferences.

This is a good idea. Then we can alert the user about exactly which key caused the problem.

> There might be a situation where there is no common denominator (eg. key1 prefers [AES128], while key2 wants [AES256] only. In such case PGPainless would fall back to a default algorithm (likely AES256).
In such a situation, should the implementation still encrypt the message (with AES256) for the key which wants AES128? Probably, right?

OpenPGP has a notion of implicit algorithms. For example, all public key supports all listed encryption mechanisms plus implicitly AES128 (in latest spec). So you'll always be able to fall back to something.

If you really can't fallback on anything acceptable, you could throw (if you wanted to be prudent) or encrypt with a reasonable default regardless of key settings (like AES128, SHA256 and so on). In this particular case it may make sense to not throw, even if it's less prudent, because whoever created that lousy key 10 years ago is probably using modern software today anyway and will be able to process the message you created even if you didn't follow the spec (I think).

> Also: If there are more than one eligible encryption subkey on a keyring, should we encrypt for each of them or select "the best" one only?

Select the best. I'd choose whichever one is valid and has the most recent signature.
