### ISSUE TITLE
Question: why PGPainess uses getKeyEncryptionAlgorithm() to determine if it is encrypted instead of analyzing presence of the S2K?

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#99]
Found this piece of code:

```
    public boolean isFullyDecrypted() {
        if (isSecretKey()) {
            for (PGPSecretKey secretKey : getSecretKeys()) {
                if (secretKey.getKeyEncryptionAlgorithm() != SymmetricKeyAlgorithm.NULL.getAlgorithmId()) {
                    return false;
                }
            }
        }
        return true;
    }
```
Is that a valid way to determine if a key is encrypted? Some other implementations in other programming languages (for example `openpgp.js`) do analyze presence/absence of the S2K.

**Comment by vanitasvitae** [comment]
This is a way I came up with during testing.
I will look into it to see if checking for S2K is the better way to do this :+1:
Thanks for bringing this to my attention :)

**Comment by IvanPizhenko** [comment]
Here's what openpgp.js does:
https://github.com/openpgpjs/openpgpjs/blob/2e19f1401ca12eec425d6e758393c8c949d60915/src/packet/secret_key.js#L149

**Comment by vanitasvitae** [comment]
I just pushed a commit that adopts openpgp.js' behavior (which also seems to be more standards compliant, looking at https://tools.ietf.org/html/rfc4880#section-3.7.2.1).

**Comment by tomholub** [comment]
Excellent!
